### ISSUE TITLE
"Full Cucumber run" causes error

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#103]
_From @Sanjo on August 20, 2015 4:51_

It seems that the connection wasn't initialized.

Reproduce:
1. Have a feature with the @dev tag
2. Start the app
3. Wait until the feature has initially run
4. Click the "Full Cucumber run" button in the html reporter

I also have CHIMP_OPTIONS set to '--watch=@dev --debug=true --log=verbose'

```
Exception while invoking method 'runAll' TypeError: Cannot call method 'call' of undefined
    at _runSingleExecutionMode (packages/xolvio:cucumber/src/mirror-server.js:120:1)
    at [object Object].Meteor.methods.runAll (packages/xolvio:cucumber/src/mirror-server.js:49:1)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:164:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
    at packages/meteorhacks:kadira/lib/hijack/wrap_session.js:52:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object].sessionProto.protocol_handlers.method (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:51:1)
    at packages/ddp/livedata_server.js:546:1
```

_Copied from original issue: xolvio/meteor-cucumber#196_

**Comment by guilrom** [comment]
Hi. Experiencing the same issue (using cucumber@0.20.2_1), in the same context :
```
Exception while invoking method 'runAll' TypeError: Cannot call method 'call' of undefined
    at _runSingleExecutionMode (meteor://�app/packages/xolvio_cucumber/meteor/src/mirror-server.js:142:1)
```
Probably unrelated, but I am also seing this in the cucumber.log during chimp startup  : 
```
node[57362] (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
```
In my case, tests are running properly but are never reported in the html reporter (which displays "cucumber mirror ready" + an infinite loading spinner). Wether using firefox or chrome produces the same behavior.
Everything was OK previously. Problems came up after upgrading meteor and adding jasmine to my project. (Jasmine is working perfectly btw, and plays nicely with the velocity html-reporter).
I tried to deactivate jasmine to run cucumber tests separately, but I still get the 2 previous errors.

**Comment by guilrom** [comment]
I am still facing this annoying problem. Any news about that ?

**Comment by samhatoum** [comment]
we've decommissioned xolvio:cucumber - please update to chimp - this shouldn't happen using it
