### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#104]
_From @dominikmayer on August 15, 2015 22:1_

I followed the instructions in the sample chapter of the Testing Meteor book and installed cucumber (OS X Yosemite, Safari/Chrome). I also did `npm install` in the cucumber directory. The html-reporter shows the following error message:

> An error occurred. Check the logs for more information.

I think this is the relevant part of the log:

```
[…]
[chimp][session-manager] requesting sessions from http://localhost:52264/wd/hub/sessions

[chimp][session-manager] received error { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'length' of undefined
  at /Users/dominik/.meteor/packages/xolvio_cucumber/.0.13.8.34kdwz++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/session-manager.js:71:19
  at Request._callback (/Users/dominik/.meteor/packages/xolvio_cucumber/.0.13.8.34kdwz++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/session-manager.js:161:7)
  at self.callback (/Users/dominik/.meteor/packages/xolvio_cucumber/.0.13.8.34kdwz++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/request/request.js:197:22)
  at Request.emit (events.js:95:17)
  at Request.onRequestError (/Users/dominik/.meteor/packages/xolvio_cucumber/.0.13.8.34kdwz++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/request/request.js:854:8)
  at ClientRequest.emit (events.js:95:17)
  at Socket.socketErrorListener (http.js:1552:9)
  at Socket.emit (events.js:95:17)
  at net.js:441:14
  at process._tickDomainCallback (node.js:486:13)

[chimp][cucumber] Closed with code 7
[chimp][cucumber] Cucumber not in a stopping state
[chimp] Finished running async processes with errors
[…]
```

_(I also posted this issue in [velocity](https://github.com/meteor-velocity/velocity/issues/366) because I don't know which package is causing it.)_

_Copied from original issue: xolvio/meteor-cucumber#195_

**Comment by samhatoum** [comment]
Just a guess, do you have java installed?

**Comment by samhatoum** [comment]
_From @dominikmayer on August 15, 2015 22:7_

I do, but Safari says I don't and sends me to the page where I already re-downloaded and re-installed Java from, just to make sure. Chrome tells me it disabled NPAPI support.

**Comment by samhatoum** [comment]
_From @dominikmayer on August 15, 2015 22:59_

I got a bit closer: I needed to allow Java for the [Oracle website](https://www.java.com/de/download/installed.jsp). The thing is: Even when I change the security settings to allow Java on all websites and restart Meteor, my problem persists. Safari tells me, that I need to install Java although Java is working on the Oracle website.

**Comment by samhatoum** [comment]
_From @Sanjo on August 16, 2015 6:11_

You can  check your Java version with `java -version` in the terminal. You should install the JDK 8. You can download it form [here](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) (Java SE Development Kit 8u51, Mac OS X x64).

**Comment by samhatoum** [comment]
_From @dominikmayer on August 16, 2015 13:37_

That was the problem. Thank you, @Sanjo. I thought I need the Java plugin but I needed to install the JDK. Maybe you want to clarify this in the installation instructions?

**Comment by samhatoum** [comment]
_From @Sanjo on August 16, 2015 13:49_

* [X] Add info about Java dependency to installation instructions of Chimp
* [X] Add info about Java dependency to installation instructions of xolvio:cucumber
* [ ] Show the user an error that he needs to install Java, when this error happens

**Comment by samhatoum** [comment]
we've decommissioned xolvio:cucumber - please update to chimp - this shouldn't happen using it
