### ISSUE TITLE
Custom Webdriver Commands not Running Synchronously

### ISSUE THREAD

**Issue by workflow** [xolvio/chimp#139]
It looks like custom webdriver commands (http://webdriver.io/api/utility/addCommand.html) aren't currently running synchronously like the rest of the webdriver code inside step definitions.

# Reproduction

Inside a step definition, run

```
        browser.addCommand('test', function() {
            this.debug();
            this.url(process.env.ROOT_URL);
            this.waitForExist('.nonexisting-element');
        });
        browser.test();
```

# Expected Outcome

`debug()` should halt the step definition synchronously, and the remaining two commands should never be executed. This is the behaviour when directly called from a step definition.

# Actual Outcome

`debug()` is triggered, but the `url()` and `waitForExist()` seem to run asynchronously without waiting for `debug()` to return.
The `waitForExist()` on a not existing element then fails after the timeout of 10 seconds.

```
[12:00:34]:  DEBUG	queue has stopped, you can now go into the browser
[12:00:34]:  DEBUG	continue by pressing the [ENTER] key ...
[12:00:34]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/url"
[12:00:34]:  DATA		 {"url":"http://localhost:39948/"}
[12:00:34]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:34]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
    When I navigate to "Sally Cucumber"'s public investor profile -> account # features/Shared/socializing/follow-user.feature:17
[12:00:34]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:34]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:34]:  RESULT		 []
[12:00:34]:  RESULT		 []
[12:00:34]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:34]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:34]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:34]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:35]:  RESULT		 null
[12:00:35]:  RESULT		 []
[12:00:35]:  RESULT		 []
[12:00:35]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:35]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:35]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:35]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:35]:  RESULT		 []
[12:00:35]:  RESULT		 []
[12:00:36]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:36]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:36]:  RESULT		 []
[12:00:36]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:36]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:36]:  RESULT		 []
[12:00:36]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:36]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:36]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:36]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:36]:  RESULT		 []
[12:00:36]:  RESULT		 []
[12:00:36]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:36]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:36]:  RESULT		 []
[12:00:36]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:36]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:36]:  RESULT		 []
[12:00:36]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:36]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:36]:  RESULT		 []
[12:00:36]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:36]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:36]:  RESULT		 []
[12:00:37]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:37]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:37]:  RESULT		 []
[12:00:37]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:37]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:37]:  RESULT		 []
[12:00:37]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:37]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:37]:  RESULT		 []
[12:00:37]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:37]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:37]:  RESULT		 []
[12:00:37]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:37]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:37]:  RESULT		 []
[12:00:37]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:37]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:37]:  RESULT		 []
[12:00:37]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:37]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:37]:  RESULT		 []
[12:00:37]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:37]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:37]:  RESULT		 []
[12:00:38]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:38]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:38]:  RESULT		 []
[12:00:38]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:38]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:38]:  RESULT		 []
[12:00:38]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:38]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:38]:  RESULT		 []
[12:00:38]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:38]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:38]:  RESULT		 []
[12:00:38]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:38]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:38]:  RESULT		 []
[12:00:38]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:38]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:38]:  RESULT		 []
[12:00:39]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:39]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:39]:  RESULT		 []
[12:00:39]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:39]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:39]:  RESULT		 []
[12:00:39]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:39]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:39]:  RESULT		 []
[12:00:39]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:39]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:39]:  RESULT		 []
[12:00:39]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:39]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:39]:  RESULT		 []
[12:00:39]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:39]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:39]:  RESULT		 []
[12:00:39]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:39]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:39]:  RESULT		 []
[12:00:39]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:39]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:39]:  RESULT		 []
[12:00:40]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:40]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:40]:  RESULT		 []
[12:00:40]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:40]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:40]:  RESULT		 []
[12:00:40]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:40]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:40]:  RESULT		 []
[12:00:40]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:40]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:40]:  RESULT		 []
[12:00:40]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:40]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:40]:  RESULT		 []
[12:00:40]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:40]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:40]:  RESULT		 []
[12:00:40]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:40]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:40]:  RESULT		 []
[12:00:41]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:41]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:41]:  RESULT		 []
[12:00:41]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:41]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:41]:  RESULT		 []
[12:00:41]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:41]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:41]:  RESULT		 []
[12:00:41]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:41]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:41]:  RESULT		 []
[12:00:41]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:41]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:41]:  RESULT		 []
[12:00:41]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:41]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:41]:  RESULT		 []
[12:00:41]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:41]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:41]:  RESULT		 []
[12:00:42]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:42]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:42]:  RESULT		 []
[12:00:42]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:42]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:42]:  RESULT		 []
[12:00:42]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:42]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:42]:  RESULT		 []
[12:00:42]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:42]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:42]:  RESULT		 []
[12:00:42]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:42]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:42]:  RESULT		 []
[12:00:42]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:42]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:42]:  RESULT		 []
[12:00:42]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:42]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:42]:  RESULT		 []
[12:00:42]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:42]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:42]:  RESULT		 []
[12:00:43]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:43]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:43]:  RESULT		 []
[12:00:43]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:43]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:43]:  RESULT		 []
[12:00:43]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:43]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:43]:  RESULT		 []
[12:00:43]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:43]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:43]:  RESULT		 []
[12:00:43]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:43]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:43]:  RESULT		 []
[12:00:43]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:43]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:43]:  RESULT		 []
[12:00:43]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:43]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:43]:  RESULT		 []
[12:00:43]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:43]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:44]:  RESULT		 []
[12:00:44]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:44]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[12:00:44]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:44]:  DATA		 {"using":"id","value":"publicUserFollow"}
[12:00:44]:  RESULT		 []
[12:00:44]:  RESULT		 []
[12:00:44]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:44]:  DATA		 {"using":"css selector","value":".nonexisting-element"}
[chimp] Detected an unhandledRejection.
[chimp][hooks] Reason:
[chimp] Detected an unhandledRejection.
[chimp][hooks] Reason:
[12:00:44]:  COMMAND	POST 	 "/wd/hub/session/6b67068a-76be-4160-9205-c985a43ae06b/elements"
[12:00:44]:  DATA		 {"using":"id","value":"publicUserFollow"}
    Then I should see a follow user button                                   # features/Shared/socializing/follow-user.feature:19
      Error: element (#publicUserFollow) still not existing after 10000ms
        at World.<anonymous> (features/Shared/socializing/step_definitions/follow-user.js:6:17)

          - - - - -


    When I click the follow user button                                      # features/Shared/socializing/follow-user.feature:21
    Then "Sally Cucumber" should now be part of my followed users            # features/Shared/socializing/follow-user.feature:23
    And I should see a nice message that confirms my action                  # features/Shared/socializing/follow-user.feature:25
    And the follow user button should not be clickable again                 # features/Shared/socializing/follow-user.feature:29


(::) failed steps (::)

Error: element (#publicUserFollow) still not existing after 10000ms
  at World.<anonymous> (features/Shared/socializing/step_definitions/follow-user.js:6:17)

    - - - - -


Failing scenarios:
features/Shared/socializing/follow-user.feature:13 # Scenario: Follow another user
```

**Comment by Sanjo** [comment]
Should be fixed in the later releases.

**Comment by workflow** [comment]
Awesome, thx @Sanjo! Really appreciating your work here.
