### ISSUE TITLE
chimp --path argument is not working

### ISSUE THREAD

**Issue by dbuarque** [xolvio/chimp#143]
Hey guys, the chimp --path argument is not working

```
> chimp --path=./tests/features --sync=false --saveScreenshots=false

[chimp] Running...
/home/dbuarque/workspace/phoenix-ui/node_modules/chimp/lib/cucumber-wrapper.js:29
    throw(e);
          ^
Error: ENOENT, no such file or directory '/home/dbuarque/workspace/phoenix-ui/features'
    at Error (native)
    at Object.fs.lstatSync (fs.js:792:18)
    at Object.realpathSync (fs.js:1383:21)
    at Object.expandPathWithRegexp (/home/dbuarque/workspace/phoenix-ui/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/argument_parser/path_expander.js:23:23)
    at /home/dbuarque/workspace/phoenix-ui/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/argument_parser/path_expander.js:9:39
    at Array.forEach (native)
    at Object.expandPathsWithRegexp (/home/dbuarque/workspace/phoenix-ui/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/argument_parser/path_expander.js:8:11)
    at Object.expandPaths (/home/dbuarque/workspace/phoenix-ui/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/argument_parser/feature_path_expander.js:6:38)
    at Object.getFeatureFilePaths (/home/dbuarque/workspace/phoenix-ui/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/argument_parser.js:49:71)
    at Object.getFeatureSources (/home/dbuarque/workspace/phoenix-ui/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/configuration.js:35:48)
[chimp] Finished running async processes with errors
[chimp] run complete with errors Cucumber steps failed
Error in chimp init Cucumber steps failed
npm ERR! Test failed.  See above for more details.
```

**Comment by jorgeer** [comment]
Can confirm. It always looks in the default location.

**Comment by samhatoum** [comment]
ok, on it

**Comment by tcurdt** [comment]
same here :-/

**Comment by samhatoum** [comment]
ok, perhaps a crappy workaround is to use a symlink until I fix this. I'm in the process of upgrading cucumber to 0.9.0 and it's just taking a little longer than I thought.

**Comment by tcurdt** [comment]
@samhatoum unfortunately not really a work around because of https://github.com/meteor/meteor/issues/330 (which is inconceivably from 2012)

**Comment by tcurdt** [comment]
I found the two defaults that need to match and make up the default location.

https://github.com/xolvio/chimp/blob/develop/bin/chimp#L14
https://github.com/cucumber/cucumber-js/blob/v0.8.1/lib/cucumber/cli/argument_parser.js#L230

For now I have changed them locally to `.features` (yuck!)

**Comment by rekotiira** [comment]
Looking at the code, it seems that argument_parser uses getSuppliedPaths() to provide the feature file paths, which looks like this:
```
    getSuppliedPaths: function getSuppliedPaths() {
      var options = self.getOptions();
      return options.argv.remain;
    },
```
So it expects the CLI to be used like: `./node_modules/.bin/chimp path/to/features`, instead of `./node_modules/.bin/chimp --path=path/to/features`
However using it like that, will give an error: "[chimp][cucumber] Directory features does not exist. Not running", so it seems that --path option is still used for something else. To get around it, you can run your tests like this, for now:
```
./node_modules/.bin/chimp --path=path/to/features --browser=chrome path/to/features
```

**Comment by rekotiira** [comment]
The above workaround fails when running in --watch mode though, the tests run ok once, but after that when saving your tests, you get an error:
```
/Users/rekotiira/Projects/sample-app/node_modules/chimp/lib/cucumberjs/cucumber-wrapper.js:29
    throw(e);
    ^

Error: ENOENT: no such file or directory, lstat '/Users/rekotiira/Projects/sample-app/features'
    at Error (native)
    at Object.fs.lstatSync (fs.js:844:18)
    at Object.realpathSync (fs.js:1444:21)
    at Object.expandPathWithRegexp (/Users/rekotiira/Projects/sample-app/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/argument_parser/path_expander.js:23:23)
    at /Users/rekotiira/Projects/sample-app/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/argument_parser/path_expander.js:9:39
    at Array.forEach (native)
    at Object.expandPathsWithRegexp (/Users/rekotiira/Projects/sample-app/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/argument_parser/path_expander.js:8:11)
    at Object.expandPaths (/Users/rekotiira/Projects/sample-app/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/argument_parser/feature_path_expander.js:6:38)
    at Object.getFeatureFilePaths (/Users/rekotiira/Projects/sample-app/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/argument_parser.js:49:71)
    at Object.getFeatureSources (/Users/rekotiira/Projects/sample-app/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/configuration.js:35:48)
```

**Comment by shrop** [comment]
I am seeing the same issue with `--watch`. I have to `cd` to `<meteor-app>/tests/cucumber` and run `chimp --watch --ddp=http://localhost:3000`, which does run features in my features folder at `<meteor-app>/tests/cucumber/features`

**Comment by thinkrapido** [comment]
@rekotiira your right.
I figured that out too.
It works, but its ugly and not usable with ```--watch```.
@samhatoum : a symllink is ugly too. Please fix this.

**Comment by dbuarque** [comment]
cool!

**Comment by thinkrapido** [comment]
Bravo!

**Comment by shrop** [comment]
@samhatoum right on! Just noticed this was working and had to say thank you!
