### ISSUE TITLE
EventEmitter memory leak detected on OSX El Captain

### ISSUE THREAD

**Issue by joshfttb** [xolvio/chimp#161]
Recently switched to a mac, getting the following error when attempting to run chimp, with both chrome and firefox:

```
Joshs-MacBook-Pro:desireMap josh$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
Joshs-MacBook-Pro:desireMap josh$ cd tests/cucumber/
Joshs-MacBook-Pro:cucumber josh$ chimp --ddp=http://localhost:3000
[chimp] Running...
(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at [object Object].addListener (events.js:239:17)
  at [object Object].once (events.js:265:8)
  at /usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:335:10
  at tryCatcher (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._resolveFromResolver (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:480:31)
  at new Promise (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:70:37)
  at [object Object].DDPClient.connect (/usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:309:10)
  at [object Object]._onTimeout (/usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:114:58)
  at Timer.listOnTimeout (timers.js:92:15)

(node) warning: possible EventEmitter memory leak detected. 11 failed listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at [object Object].addListener (events.js:239:17)
  at [object Object].once (events.js:265:8)
  at /usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:336:10
  at tryCatcher (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._resolveFromResolver (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:480:31)
  at new Promise (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:70:37)
  at [object Object].DDPClient.connect (/usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:309:10)
  at [object Object]._onTimeout (/usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:114:58)
  at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by joshfttb** [comment]
Wondering if this is the OSX version of https://github.com/xolvio/chimp/issues/153, installing with npm install vs npm install -g seems to fix this problem as well

**Comment by samhatoum** [comment]
Thanks for reporting, will look into it

**Comment by samhatoum** [comment]
I can't seem to replicate. Have you seen this since?

**Comment by samhatoum** [comment]
I'm also on el-captian now

**Comment by samhatoum** [comment]
I found the cause of this. It only happens if you run chimp with Meteor and the Meteor app is down

**Comment by samhatoum** [comment]
solution: make sure Meteor app is running before and during chimp being connected to a meteor app.

**Comment by romant** [comment]
Just came across it.

Running a built (namely from `node main.js`) Meteor app inside a Docker container, based off `meteorhacks/meteord:onbuild`.

Ends up throwing:

```
± sc git:(develop) chimp --ddp=http://192.168.153.128 --watch --path=tests
[chimp] Watching features with tagged with @dev,@watch,@focus
[chimp] Running...
(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:179:15)
    at once (events.js:204:8)
    at /usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:342:10
    at tryCatcher (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:70:37)
    at DDPClient.connect (/usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:310:10)
    at null._onTimeout (/usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:114:58)
    at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by samhatoum** [comment]
are you starting the meteor app first?

**Comment by romant** [comment]
I swear .. you don't sleep :smile: 

yes. It's most definitely running.

**Comment by samhatoum** [comment]
sleep is for the week :p

does it happen every time or intermittent? Does the ddp connection from chimp not work at all from specs?

**Comment by romant** [comment]
ha!

it doesn't work at all. Literally just built it; and tried to write (few) tests against it.

Failed on contact.

**Comment by samhatoum** [comment]
that would help a lot. Just be sure that you can connect to the DDP at `--ddp=http://192.168.153.128`. That error is typically when a DDP connection can't be made.

**Comment by romant** [comment]
@samhatoum [here](https://github.com/romant/chimp-o) you go.

or on your machine run :

```
export ROOT_URL="http://[IP_OF_YOUR_CONTAINER_HOST]"

docker run -d --name chimp-o -p 80:80 -e ROOT_URL=$ROOT_URL romant/chimp-o

chimp --watch --ddp=$ROOT_URL --path=tests
```

**Comment by romant** [comment]
Hi @samhatoum,

Wondering if you've had a chance to run the above ?, and if there's anything else I can provide to help reproduce the issue …?

Many thanks :smile:

**Comment by romant** [comment]
By the way - just noticed the same error on CircleCI whilst using the provided `circle.yml`
![pasted_image_14_01_2016__21_37](https://cloud.githubusercontent.com/assets/49066/12322285/2a746908-bb07-11e5-9c08-8759065bfa46.jpg)

**Comment by romant** [comment]
Hi @samhatoum 

This is still an issue. Both in OSX, and as I showed even when running against a Docker container; and even when in CircleCI.

Can you suggest work-arounds ? As the making sure that meteor is running first, isn't enough.

**Comment by DominikGuzei** [comment]
Just ran into the same problem while trying if our test suite could be made faster by pre-building Meteor on CircleCi instead of using the horrible `meteor` tool that failed to incorporate any best practices regarding performance and startup caching … any solutions for connecting chimp to a built Meteor app?

**Comment by samhatoum** [comment]
@romant sorry I totally forgot this issue. I've reenabled notifications from this repo.

@DominikGuzei does the problem also happen locally? Are you rebuilding without docker? Would be great to have some steps to replicate or better yet a repro without docker

**Comment by DominikGuzei** [comment]
@samhatoum yes i only tried it locally – built the Meteor app and started it up, then tried to run chimp pointing at the right port and mongo url but im just getting the event emitter error like posted by @romant above.

**Comment by samhatoum** [comment]
so I can't seem to repeat this. I've got a local simple built app running with a node command. I'm running chimp against it using:

chimp --ddp=http://localhost:3000 --watch

Works great.

Can you help me replicate?

**Comment by DominikGuzei** [comment]
@samhatoum can you tell me a bit more about which node versions you are using for each command (building, running chimp, starting the built app etc.)? These problems could be related to using the wrong node versions i guess.

**Comment by samhatoum** [comment]
Ah probably. I'm using 4.3.0 to run the built meteor app.

Latest Chimp 0.34.1

**Comment by DominikGuzei** [comment]
@samhatoum ok thanks, will try it with that one and see if the problems remains.

**Comment by samhatoum** [comment]
I'm on the [xolv.io/community](http://xolv.io/community) slack channel if you need any help
