### ISSUE TITLE
meteor running velocity cucumber test exception with phantomjs

### ISSUE THREAD

**Issue by ashersz** [xolvio/chimp#169]
I am trying to run cucumber test with phantomjs from the command line
If I remove the env variable SELENIUM_BROWSER=PhantomJS it runs fine
I get the following exception
```
Exception in handling DDP message: TypeError: Cannot call method 'join' of undefined
here is the command line
ROOT_URL=http://localhost:3000 \
MONGO_URL=mongodb://localhost:$1/kh_db \
CLUSTER_SERVICE=web \
CLUSTER_DISCOVERY_URL=mongodb://localhost:$1/kh_db \
CLUSTER_PUBLIC_SERVICES=search \
CLUSTER_ENDPOINT_URL=http://localhost:3000 \
JASMINE_BROWSER=PhantomJS \
SELENIUM_BROWSER=PhantomJS \
PHANTOMJS_BIN=/usr/local/bin/phantomjs \
VELOCITY_DEBUG=1 \
meteor --test 

excerpt from the console log

I20151202-17:29:08.595(2)? [velocity] Mirror process forked with pid 15771
I20151202-17:29:08.595(2)? [velocity] cucumber is starting a mirror at http://localhost:60032/.
I20151202-17:29:08.595(2)? [velocity] You can see the mirror logs at: tail -f /Volumes/code/cuapi/web/.meteor/local/log/cucumber.log
I20151202-17:29:08.595(2)? [sanjo:jasmine]: No tests for jasmine-client-integration found. Reporting completed.
I20151202-17:29:08.595(2)? [sanjo:jasmine]: No tests for jasmine-server-integration found. Reporting completed.
PASSED jasmine-client-unit : HomeCtrl => data selected index should return 0 when there is no user card
PASSED jasmine-client-unit : HomeCtrl => data selected index should return 1 when there is one user card
I20151202-17:29:12.733(2)? jasmine-client-unit: 3 tests passed (36ms)
PASSED jasmine-client-unit : HomeCtrl => newsFeedCards topics should match John Lennon
I20151202-17:29:40.828(2)? [velocity] Mirror registered. Handshaking with mirror... { framework: 'cucumber',
I20151202-17:29:40.828(2)?   host: 'http://localhost:60032/',
I20151202-17:29:40.828(2)?   port: '60032' }
I20151202-17:29:40.884(2)? [velocity] Connected to mirror, setting state to ready { framework: 'cucumber',
I20151202-17:29:40.884(2)?   host: 'http://localhost:60032/',
I20151202-17:29:40.884(2)?   port: '60032' }
I20151202-17:29:40.906(2)? [velocity] Parent Handshake response undefined undefined
Exception in handling DDP message: TypeError: Cannot call method 'join' of undefined
    at Object.connection.registerStore.update (/tools/runners/run-velocity.js:53:44)
    at Object.store.(anonymous function) [as update] (packages/ddp-client/livedata_connection.js:446:1)
    at packages/ddp-client/livedata_connection.js:1226:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at packages/ddp-client/livedata_connection.js:1225:1
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at [object Object]._.extend._livedata_data (packages/ddp-client/livedata_connection.js:1222:1)
    at onMessage (packages/ddp-client/livedata_connection.js:252:1)
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
    at packages/meteor/dynamics_nodejs.js:123:1
    at packages/ddp-client/stream_client_nodejs.js:197:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at packages/ddp-client/stream_client_nodejs.js:196:1
    at packages/ddp-client/stream_client_nodejs.js:172:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20151202-17:29:48.315(2)? cucumber: 0 tests passed
W20151202-17:29:48.316(2)? (STDERR) cucumber: 1 tests failed
W20151202-17:29:48.316(2)? (STDERR) An error occurred. Check the logs for more information.
W20151202-17:29:48.316(2)? (STDERR) undefined
W20151202-17:29:48.317(2)? (STDERR) undefined
FAILURE
```
From the cucumber.txt (log) it seems that a driver for PhantomJS is missing.
What should I do? Thanks for answering.

```
[cucumber .txt](https://github.com/xolvio/chimp/files/49878/cucumber.txt)
[versions.txt](https://github.com/xolvio/chimp/files/49879/versions.txt)
[packages.txt](https://github.com/xolvio/chimp/files/49880/packages.txt)
 ```

**Comment by diegolaguna** [comment]
I had a similar issue with SELENIUM_BROWSER=PhantomJS
I had to replace it with SELENIUM_BROWSER=phantomjs in lowercase, that worked for me.

**Comment by samhatoum** [comment]
@diegolaguna is correct. Also, be very aware of the problems you will face with Meteor + phantom. Too many headaches to make it worth it in our opinion

**Comment by ashersz** [comment]
@samhatoum So how would you run tests on a jenkins linux machine? I also installed cucumber-junit-reporter for the reports.

**Comment by samhatoum** [comment]
you can use `xvfb` and run chrome headless
https://gist.github.com/addyosmani/5336747

**Comment by logankoester** [comment]
@samhatoum I'm curious what kind of problems with Meteor + phantom you are referring to. Would you mind elaborating or pointing me toward some issues people have experienced?

**Comment by samhatoum** [comment]
@logankoester routing was one minor issue where Phantom didn't support the `url` object out the box. I found other small issues like this and odd ones like "stale element refrence" that are difficult to debug whereas chrome works flawlessly

**Comment by samhatoum** [comment]
@ashersz may I close this issue now?

**Comment by ashersz** [comment]
@samhatoum you can close the issue, I will try using xvfb, by the way I have a question is it possible to override karma.conf and if so how? Again thanks for this very useful project.
