### ISSUE TITLE
CI: Asynchronous script timeout: result was not received in 10 seconds

### ISSUE THREAD

**Issue by jamiecollinson** [xolvio/chimp#171]
Hoping someone can help - my tests are running perfectly locally, but on circleci I'm - intermittently, these steps are used in several features - getting the following failures:

```
Error: asynchronous script timeout: result was not received in 10 seconds
  at World.<anonymous> (features/hooks.js:10:8)

    - - - - -


Error: asynchronous script timeout: result was not received in 10 seconds
  at World.<anonymous> (features/_steps/_common.js:60:13)

    - - - - -
```

The files look like:
```
// hooks.js
module.exports = function( ) {

  // called before each scenario
  this.Before(function() {
    browser.setViewportSize({
      width: 1200,
      height: 700
    });
    browser.url(process.env.ROOT_URL);
    server.call('reset');
  });

};
```
```
// global_fixtures.js
Meteor.methods({

  // We call this before EVERY test scenario - it should completely reset the
  reset: function() {

    // Reset unpartitioned collections
    Tenants.direct.remove({});
    Meteor.users.direct.remove({});
    Notifications.direct.remove({});

    // Reset partitioned collections
    Partitioner.directOperation(function() {
      //Entities dependent on other entities should be first
      Tasks.direct.remove({});
      Activities.direct.remove({});
      Meteor.tags.direct.remove({});
      AuditLog.direct.remove({});
      Companies.direct.remove({});
      Contacts.direct.remove({});
      Projects.direct.remove({});
      PurchaseOrders.direct.remove({});
      PurchaseOrderItems.direct.remove({});
      Chatterbox.direct.remove({});
      Products.direct.remove({});
    });

    // Reset server session variables. At the moment (annoyingly)
    // we can't do something like Mongo.serversession.remove({}) because we h
    // no handle to the collection and meteor doesn't allow us to look up a
    // collection from the mongo name
    ServerSession.set('maintenance', false);

  }
});
```
```
// _common.js
module.exports = function() {

  var logout = function(done) {
    Meteor.logout(done);
  };

  var login = function(email, password, done) {
    Meteor.loginWithPassword(email, password, done);
  };

  var url = require('url');

  this.Given(/^I (am a logged out user|log out)$/, function() {
    browser.executeAsync(logout);
  });

  this.Given(/^I am a logged in user$/, function() {
    // FILE TRUNCATED, BUT THE FOLLOWING IS LINE 60
    browser.executeAsync(login, 'test@domain.com', 'goodpassword');
  });

});
```

Am I doing something obviously silly? Should I not be using the `executeAsync` functions since the move to sync style tests? I've compared with the example letterpress tests and the style at least seems similar.

We're quite pleased with our test suite, but not being able to run reliably on CI is starting to really slow us down so I'd love to be able to resolve the issues we're having.

**Comment by Sanjo** [comment]
Looks ok to me. Try to logout before you do the reset.

**Comment by jamiecollinson** [comment]
@Sanjo - doesn't seem to make any difference. I seem to sporadically get this sort of issue whenever I'm using the browser to call a `Meteor.method`. I do this in cases where I want to perform an action which is already tested elsewhere - e.g. we have tests for the login UI, but when that isn't what we're trying to test it's convenient to shortcut and use `Meteor.loginWithPassword()`. Perhaps this isn't best practice?

**Comment by samhatoum** [comment]
you should always try to bypass the UI for these situations so it is best practice. A repro would really help us help
