### ISSUE TITLE
EventEmitter Memory Leak Message When Meteor App is Down

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#189]
Need to modify the xolvio-ddp package to provide a better error when this occurs

**Comment by kalinchernev** [comment]
Thanks for noticing, I could confirm getting the error:
```
 chimp --ddp=http://localhost:3000 --watch
[chimp] Watching features with tagged with @dev,@watch,@focus
[chimp] Running...
[chimp][cucumber] Directory features does not exist. Not running
(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:240:17)
    at once (events.js:266:8)
    at /usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:342:10
    at tryCatcher (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:70:37)
    at DDPClient.connect (/usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:310:10)
    at null._onTimeout (/usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:114:58)
    at Timer.listOnTimeout (timers.js:93:15)
(node) warning: possible EventEmitter memory leak detected. 11 failed listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:240:17)
    at once (events.js:266:8)
    at /usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:343:10
    at tryCatcher (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:70:37)
    at DDPClient.connect (/usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:310:10)
    at null._onTimeout (/usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:114:58)
    at Timer.listOnTimeout (timers.js:93:15)

```

**Comment by samhatoum** [comment]
thanks, that'll help new comers to find the cause. Solution is to start Meteor first. We're working on a better message

**Comment by kalinchernev** [comment]
Honestly, I didn't manage to make it work on running state.
I tried starting both with [meteor-starter](https://github.com/yogiben/meteor-starter) and normal latest core. 
The error is not thrown, but the browser doesn't get opened and it remains at `[chimp][cucumber] Directory features does not exist. Not running`

**Comment by samhatoum** [comment]
You need to create a directory called `/features` and make sure you have a feature file int here.

you can point to that either by supplying the `--path=<dir>/features` param, or by going to the dir containing `/features` and running chimp from there

**Comment by kalinchernev** [comment]
Thank you, Sam, it worked of course!
I totally go into newcomers category now! :)

**Comment by samhatoum** [comment]
This script should help with the original error
https://gist.github.com/samhatoum/d46fc75e1474aaff22d2

**Comment by samhatoum** [comment]
and welcome @kalinchernev
