### ISSUE TITLE
unable to run chimp on circleCI

### ISSUE THREAD

**Issue by Alino** [xolvio/chimp#192]
I am installing chimp on circleCI with ```npm install chimp -g``` but when I try to run ```chimp``` I get this error:
```
ubuntu@box1029:~$ chimp
[chimp] Running...
selenium-standalone installation [==================  ] 92% 0.0s
/home/ubuntu/nvm/v0.10.33/lib/node_modules/chimp/node_modules/selenium-standalone/lib/install.js:248
  fs.access(where, fs.R_OK | fs.X_OK, function(err) {
     ^
TypeError: Object #<Object> has no method 'access'
    at chmodChromeDr (/home/ubuntu/nvm/v0.10.33/lib/node_modules/chimp/node_modules/selenium-standalone/lib/install.js:248:6)
    at /home/ubuntu/nvm/v0.10.33/lib/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:699:13
    at iterate (/home/ubuntu/nvm/v0.10.33/lib/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:256:13)
    at /home/ubuntu/nvm/v0.10.33/lib/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:268:29
    at /home/ubuntu/nvm/v0.10.33/lib/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:40:16
    at /home/ubuntu/nvm/v0.10.33/lib/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:705:17
    at Object._onImmediate (/home/ubuntu/nvm/v0.10.33/lib/node_modules/chimp/node_modules/selenium-standalone/lib/install.js:223:5)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by samhatoum** [comment]
try updating node, 0.10.33 is too old :)

**Comment by Alino** [comment]
oh I wasn't giving attention to node versions. Thank you :)

**Comment by mordka** [comment]
I had same error on v0.10.40 which disappeared after switching to v0.12.7. Though, I'm not sure, if it's the right move to switch branches because of a testing library.

**Comment by zvictor** [comment]
Although I have node version set as 5.2.0 in my circle.yml, I still get this error when I am debugging something on CLI through SSH. If you have the some problem, just use nvm to help you out:

```haskell
$ nvm use 5.2.0
```

**Comment by samhatoum** [comment]
Did you try blowing the cache?

**Comment by zvictor** [comment]
How should I do that? "Rebuild without cache" does not help.

**Comment by samhatoum** [comment]
yes, that's what I meant!

It's really odd, and I'm guessing it's a circle issue. Thanks for posting back here
