### ISSUE TITLE
Error when installing on Windows

### ISSUE THREAD

**Issue by tomaszzar** [xolvio/chimp#196]
I'm using:
Windows 8.1 x64
node v4.2.3
npm 2.14.7
java version "1.8.0_45"
Python 2.7 (added it to the system path c:\Python27\python.exe and PYTHON env variable)
Visual Studio Community 2013 (also tried with 2015)

When trying to install chimp I'm getting this:

```
c:\work\todos>npm install chimp -g
npm WARN optional dep failed, continuing fsevents@0.3.8

> fibers@1.0.8 install C:\Users\Tomek\AppData\Roaming\npm\node_modules\chimp\node_modules\fibers
> node build.js || nodejs build.js

/
C:\Users\Tomek\AppData\Roaming\npm\node_modules\chimp\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp
.js" rebuild --release )  else (node  rebuild --release )
gyp: c:\Program Files\nodejs"\common.gypi not found (cwd: C:\Users\Tomek\AppData\Roaming\npm\node_modules\chimp\node_modules\fibers) while reading includes of binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\Tomek\AppData\Roaming\npm\node_modules\chimp\node_modules\fibers
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "chimp" "-g"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.8 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.8 install script 'node build.js || nodejs build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\work\todos\npm-debug.log

c:\work\todos>
```
Any help?

**Comment by samhatoum** [comment]
Fibers can be a bit funny on different setups. Can you try without the `-g` flag, and failing that, try to update node to 5.2.0

**Comment by tomaszzar** [comment]
Updating node to 5.2.0 solved the problem. Thank you!
