### ISSUE TITLE
Cannot run chimp to test Meteor app

### ISSUE THREAD

**Issue by vhmh2005** [xolvio/chimp#201]
I couldn't run chimp. I thought node version could be an issue. Then I tried different versions of node but still no luck. 

Below is what I got when trying to run chimp (Meteor app already started on port 3000)

### node version 0.10.36 and 0.10.41

```
~/htdocs/reward$ nvm install 0.10.36
######################################################################## 100.0%
Now using node v0.10.36 (npm v1.4.28)
~/htdocs/reward$ chimp --watch --ddp=http://localhost:3000
[chimp] Watching features with tagged with @dev,@watch,@focus
[chimp] Running...

/usr/local/lib/node_modules/chimp/node_modules/selenium-standalone/lib/install.js:248
  fs.access(where, fs.R_OK | fs.X_OK, function(err) {
     ^
TypeError: Object #<Object> has no method 'access'
    at chmodChromeDr (/usr/local/lib/node_modules/chimp/node_modules/selenium-standalone/lib/install.js:248:6)
    at /usr/local/lib/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:699:13
    at iterate (/usr/local/lib/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:256:13)
    at /usr/local/lib/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:268:29
    at /usr/local/lib/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:40:16
    at /usr/local/lib/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:705:17
    at Object._onImmediate (/usr/local/lib/node_modules/chimp/node_modules/selenium-standalone/lib/install.js:223:5)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
~/htdocs/reward$ $(brew --prefix nvm)
-bash: /usr/local/opt/nvm: is a directory
~/htdocs/reward$ $(brew --prefix nvm)
```

### node version 0.12.9 and above

```
~/htdocs/reward$ nvm install 0.12.9
nvm use 0.12.9
######################################################################## 100.0%
Now using node v0.12.9 (npm v2.14.9)
~/htdocs/reward$ nvm use 0.12.9
Now using node v0.12.9 (npm v2.14.9)
~/htdocs/reward$ chimp --watch --ddp=http://localhost:3000
/usr/local/lib/node_modules/chimp/node_modules/fibers/fibers.js:16
	throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
	      ^
Error: `/usr/local/lib/node_modules/chimp/node_modules/fibers/bin/darwin-x64-v8-3.28/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/usr/local/lib/node_modules/chimp/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/index.js:7:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/chimp/lib/session-manager.js:37:38)
    at Module._compile (module.js:460:26)
```

**Comment by samhatoum** [comment]
try node 5.2.0

**Comment by vhmh2005** [comment]
thanks @samhatoum , now I get this error:

```
~/htdocs/reward/tests/cucumber$ chimp --watch --ddp=http://localhost:3000
[chimp] Watching features with tagged with @dev,@watch,@focus
[chimp] Running...
(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:240:17)
    at once (events.js:266:8)
    at /usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:342:10
    at tryCatcher (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:70:37)
    at DDPClient.connect (/usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:310:10)
    at null._onTimeout (/usr/local/lib/node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js:114:58)
    at Timer.listOnTimeout (timers.js:93:15)
```

**Comment by samhatoum** [comment]
Be sure to start Meteor first :)

**Comment by vhmh2005** [comment]
My bad, I had stopped Meteor. Thanks @samhatoum

**Comment by samhatoum** [comment]
np!
