### ISSUE TITLE
Basic test failing

### ISSUE THREAD

**Issue by tomaszzar** [xolvio/chimp#205]
Hi,

I've tried to run a basic test that was working using xolvio:cucumber but been struggling to get it working now...

```
Scenario:
    Given I am a new user
    When I navigate to "/"
    Then I should see the title "intentional failure"
```
Here are the step definitions
```
    module.exports = function () {

        var url = require('url');

        this.Given(/^I am a new user$/, function (callback) {
            callback();
        });

        this.When(/^I navigate to "([^"]*)"$/, function (relativePath) {
            // WebdriverIO supports Promises/A+ out the box, so you can return that too
            return this.client. // this.browser is a pre-configured WebdriverIO + PhantomJS instance
                url(url.resolve(process.env.ROOT_URL, relativePath)); // process.env.ROOT_URL always points to the mirror
        });

        this.Then(/^I should see the title "([^"]*)"$/, function (expectedTitle) {
            // you can use chai-as-promised in step definitions also
            return this.client.
                waitForVisible('body *'). // WebdriverIO chain-able promise magic
                getTitle().should.become(expectedTitle);
        });
    }
```
Here's the output:
```
  Scenario:                                           # features\homepage.feature:8
    Given I am a new user                             # features\homepage.feature:9
    When I navigate to "/"                            # features\homepage.feature:10
      TypeError: Parameter 'url' must be a string, not undefined
        at World.<anonymous> (features\step_definitions\homepage.js:18:25)

    Then I should see the title "intentional failure" # features\homepage.feature:11


(::) failed steps (::)

TypeError: Parameter 'url' must be a string, not undefined
  at World.<anonymous> (features\step_definitions\homepage.js:18:25)


Failing scenarios:
features\homepage.feature:8 # Scenario:

1 scenario (1 failed)
3 steps (1 failed, 1 skipped, 1 passed)
```
Any help?

**Comment by samhatoum** [comment]
Hey, that syntax won't work. See this:
https://chimp.readme.io/v1.0/docs/migrating-from-xolviocucumber-to-chimp



Try:
```
this.Given(/^I am a new user$/, function () {
});

this.When(/^I navigate to "([^"]*)"$/, function (relativePath) {
  client.url(url.resolve(process.env.ROOT_URL, relativePath));
});

this.Then(/^I should see the title "([^"]*)"$/, function (expectedTitle) {
  client.waitForVisible('body *');
  expect(client.getTitle().to.be(expectedTitle));
});
```

**Comment by tomaszzar** [comment]
Ok, that works. Thank you!
