### ISSUE TITLE
Cannot install chimp

### ISSUE THREAD

**Issue by kalinchernev** [xolvio/chimp#208]
node -v: v4.2.3
npm -v: 3.5.2

Java:
```
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

Error:
```
> fibers@1.0.8 install /home/kalin/projects/meteor-tests/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory `/home/kalin/projects/meteor-tests/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
make: g++: Command not found
make: *** [Release/obj.target/fibers/src/fibers.o] Error 127
make: Leaving directory `/home/kalin/projects/meteor-tests/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-42-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/kalin/projects/meteor-tests/node_modules/fibers
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
Build failed
make: Entering directory `/home/kalin/projects/meteor-tests/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
make: g++: Command not found
make: *** [Release/obj.target/fibers/src/fibers.o] Error 127
make: Leaving directory `/home/kalin/projects/meteor-tests/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-42-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/kalin/projects/meteor-tests/node_modules/fibers
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
Build failed
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8
npm WARN enoent ENOENT: no such file or directory, open '/home/kalin/projects/meteor-tests/package.json'
npm WARN meteor-tests No description
npm WARN meteor-tests No repository field.
npm WARN meteor-tests No README data
npm WARN meteor-tests No license field.
npm ERR! Linux 3.19.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "chimp"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.8 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@1.0.8 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kalin/projects/meteor-tests/npm-debug.log
```

The OS is clean Xubuntu 14.04 LTS. What could be wrong in the environment?

Thanks for your help.

**Comment by samhatoum** [comment]
Try updating Node to 5.2.0

**Comment by kalinchernev** [comment]
It worked, thank you for the quick reply!

**Comment by samhatoum** [comment]
:) I'll update the readme. I think it's just a few versions in the middle that didn't work with Fibers
