### ISSUE TITLE
Issue installing on OSX El Capitan

### ISSUE THREAD

**Issue by adamgins** [xolvio/chimp#222]
Hi,

I am having issues running t

I get

```
npm install -g chimp
npm http GET https://registry.npmjs.org/chimp
npm http 304 https://registry.npmjs.org/chimp
npm ERR! error rolling back Error: EACCES, unlink '/usr/local/lib/node_modules/chimp'
npm ERR! error rolling back  chimp@0.24.1 { [Error: EACCES, unlink '/usr/local/lib/node_modules/chimp']
npm ERR! error rolling back   stack: 'Error: EACCES, unlink \'/usr/local/lib/node_modules/chimp\'',
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/chimp' }
npm ERR! Error: EACCES, unlink '/usr/local/lib/node_modules/chimp'
npm ERR!  { [Error: EACCES, unlink '/usr/local/lib/node_modules/chimp']
npm ERR!   stack: 'Error: EACCES, unlink \'/usr/local/lib/node_modules/chimp\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/chimp' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator
```

I tried sudo and see this

```
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/sntp

> fsevents@0.3.8 install /usr/local/lib/node_modules/chimp/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild


gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/adamginsburg/.node-gyp/0.11.12"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/chimp/node_modules/chokidar/node_modules/fsevents/.node-gyp"
gyp http GET http://nodejs.org/dist/v0.11.12/node-v0.11.12.tar.gz


gyp http 200 http://nodejs.org/dist/v0.11.12/node-v0.11.12.tar.gz

gyp: binding.gyp not found (cwd: /usr/local/lib/node_modules/chimp/node_modules/chokidar/node_modules/fsevents)
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1045:12)
gyp ERR! System Darwin 15.2.0
```
I tried the alternatives `npm install chimp` and `sudo npm install chimp` and get errors too... Any ideas, pls?

**Comment by Sanjo** [comment]
I would recommend you to use [nvm](https://github.com/creationix/nvm#install-script), to install node. And use the latest version of node.js (5.4).
