### ISSUE TITLE
Can't start chimp with --ddp flag

### ISSUE THREAD

**Issue by andreasseiler** [xolvio/chimp#226]
When I try to start chimp with the --ddp flag it throws the following error:

Any idea on how to fix this?

<pre><code>
C:\Users\RW\AppData\Roaming\npm\node_modules\chimp\lib\ddp-watcher.js:18
  if (ddpHost.indexOf('http://') === -1 && ddpHost.indexOf('https://') === -1) {
              ^

TypeError: ddpHost.indexOf is not a function
    at AutoupdateWatcher._getUrl (C:\Users\RW\AppData\Roaming\npm\node_modules\chimp\lib\ddp-watcher.js:18:15)
    at new AutoupdateWatcher (C:\Users\RW\AppData\Roaming\npm\node_modules\chimp\lib\ddp-watcher.js:10:20)
    at Chimp.watch (C:\Users\RW\AppData\Roaming\npm\node_modules\chimp\lib\chimp.js:159:29)
    at Chimp.selectMode (C:\Users\RW\AppData\Roaming\npm\node_modules\chimp\lib\chimp.js:125:10)
    at Chimp.init (C:\Users\RW\AppData\Roaming\npm\node_modules\chimp\lib\chimp.js:83:8)
    at startChimp (C:\Users\RW\AppData\Roaming\npm\node_modules\chimp\bin\chimp:77:9)
    at C:\Users\RW\AppData\Roaming\npm\node_modules\chimp\bin\chimp:64:7
    at Server.<anonymous> (C:\Users\RW\AppData\Roaming\npm\node_modules\chimp\node_modules\freeport\lib\freeport.js:11:5)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1523:8)
    at nextTickCallbackWith1Arg (node.js:463:9)
    at process._tickDomainCallback (node.js:426:17)
    at Function.Module.runMain (module.js:431:11)
    at startup (node.js:139:18)
    at node.js:999:3
</code></pre>

**Comment by samhatoum** [comment]
try to pass in `--ddp=http://localhost:3000` - you need to pass in `http`

**Comment by andreasseiler** [comment]
Thanks! It worked!
