### ISSUE TITLE
Can't wait without a fiber when using waitUntil

### ISSUE THREAD

**Issue by area** [xolvio/chimp#270]
The relevant code snippet:

```
client.url('http://127.0.0.1:3000')
var login = function(email, password) {
	Meteor.loginWithPassword(email, password)
}
var isLoggedIn = function(){
	return Meteor.user()!==null
}
client.execute(login, user.email, user.password)
client.waitUntil(function() {
	var res = client.execute(isLoggedIn)
	return res.value===true
});
```

I get:
```
[chimp] Detected an unhandledRejection.
[chimp][hooks] Reason:
[chimp][hooks] Can't wait without a fiber
```

which goes away when I remove the `waitUntil`. If I change the `waitUntil` call to 

```
client.waitUntil(function() {
	return true
})
```
then I get

```
[chimp] Detected an unhandledRejection.
[chimp][hooks] Reason:
[chimp][hooks] promise.then is not a function
```

What am I doing wrong with `waitUntil`?

**Comment by area** [comment]
This seems oddly similar to https://github.com/xolvio/chimp/issues/214, though I'm using the version of `chimp` installed from `npm`

**Comment by Sanjo** [comment]
Are you using Chimp 0.26.0 or newer?

**Comment by area** [comment]
Yep, 0.27.0

**Comment by Sanjo** [comment]
It's now fixed in xolvio-sync-webdriverio@4.0.8. A `npm update chimp` should do it I think.

**Comment by area** [comment]
Thanks for fixing so quickly! This update seems to have introduced a different bug though, which I'll make a new issue for.

**Comment by rsshilli** [comment]
I am also receiving this "Can't wait without a fiber" error and I'm just running a method wrapped in an wrapAsyncObject() command.  My stack trace below tells me I've probably hit the same issue.

I've tried to update chimp (I'm on 0.46.0). Running an `npm list -g` says I'm using xolvio-sync-webdriverio@8.0.0.  How do I get onto 4.0.8?

Here's the stack trace I'm seeing:

    [chimp][hooks] Error: Can't wait without a fiber
        at Function.wait (C:\Users\ryans\AppData\Roaming\npm\node_modules\chimp\node_modules\xolvio-sync-webdriverio\node_modules\fibers\future.js:159:9)
        at Object.Future.wait (C:\Users\ryans\AppData\Roaming\npm\node_modules\chimp\node_modules\xolvio-sync-webdriverio\node_modules\fibers\future.js:448:10)
        at Object.<anonymous> (C:\Users\ryans\AppData\Roaming\npm\node_modules\chimp\node_modules\xolvio-sync-webdriverio\node_modules\xolvio-fiber-utils\index.js:48:19)
        at null.<anonymous> (C:/projects/cherrycircle/build/test/features/support/user_steps.js:17:24)
        at null.tryCatcher (C:\projects\cherrycircle\node_modules\sequelize\node_modules\bluebird\js\release\util.js:16:23)
        at Promise._settlePromiseFromHandler (C:\projects\cherrycircle\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:510:31)
        at Promise._settlePromise (C:\projects\cherrycircle\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:567:18)
        at Promise._settlePromise0 (C:\projects\cherrycircle\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:612:10)
        at Promise._settlePromises (C:\projects\cherrycircle\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:691:18)
        at Async._drainQueue (C:\projects\cherrycircle\node_modules\sequelize\node_modules\bluebird\js\release\async.js:133:16)
        at Async._drainQueues (C:\projects\cherrycircle\node_modules\sequelize\node_modules\bluebird\js\release\async.js:143:10)
        at Immediate.Async.drainQueues [as _onImmediate] (C:\projects\cherrycircle\node_modules\sequelize\node_modules\bluebird\js\release\async.js:17:14)
        at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by rsshilli** [comment]
I figured out what was wrong in my case.  I had wrapped an import in wrapAsyncObject() and then again wrapped it in an wrapAsync() call.  To fix this, I removed the wrapAsyncObject() call (I just required it normally) and then kept my function in wrapAsync() which took care of everything.
