### ISSUE TITLE
Error installing Chimp...

### ISSUE THREAD

**Issue by mario-ortiz** [xolvio/chimp#287]
Not sure if this is a local issue, but I'm having a problem installing Chimp from scratch, I have a different version in another project, but trying to install latest 0.30.0. For some reason I'm getting a lot of errors regarding not being able to connect to the github repository. 

I'm behind a corporate PROXY, but I was able to install the previous version of chimp and other packages without problems just by adding a couple lines to the .npmrc file, but I'm still getting an error when trying to install the latest version.

This is a fraction of the error log.

I'm going to try to install it at home to make sure if its a Proxy issue.

```
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:821:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child
_process.js:211:5)
npm WARN addRemoteGit  xolvio/cucumber-js#v0.9.4-chimp.2 resetting remote C:\Use
rs\sg0951798\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xolvio-cucumb
er-js-git-ad3c9ca5 because of error: { [Error: Command failed: git -c core.longp
aths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git clone --template=C:\Users\sg0951798\AppData\Roaming\npm-cache\_git-
remotes\_templates --mirror git://github.com/xolvio/cucumber-js.git C:\Users\sg0
951798\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xolvio-cucumber-js-
git-ad3c9ca5: Cloning into bare repository 'C:\Users\sg0951798\AppData\Roaming\n
pm-cache\_git-remotes\git-github-com-xolvio-cucumber-js-git-ad3c9ca5'...
npm ERR! git clone --template=C:\Users\sg0951798\AppData\Roaming\npm-cache\_git-
remotes\_templates --mirror git://github.com/xolvio/cucumber-js.git C:\Users\sg0
951798\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xolvio-cucumber-js-
git-ad3c9ca5: fatal: unable to access 'https://github.com/xolvio/cucumber-js.git
/': Proxy CONNECT aborted
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:821:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child
_process.js:211:5)
npm WARN addRemoteGit  xolvio/cucumber-js#v0.9.4-chimp.2 resetting remote C:\Use
rs\sg0951798\AppData\Roaming\npm-cache\_git-remotes\https-github-com-xolvio-cucu
mber-js-git-21813647 because of error: { [Error: Command failed: git -c core.lon
gpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git clone --template=C:\Users\sg0951798\AppData\Roaming\npm-cache\_git-
remotes\_templates --mirror https://github.com/xolvio/cucumber-js.git C:\Users\s
g0951798\AppData\Roaming\npm-cache\_git-remotes\https-github-com-xolvio-cucumber
-js-git-21813647: Cloning into bare repository 'C:\Users\sg0951798\AppData\Roami
ng\npm-cache\_git-remotes\https-github-com-xolvio-cucumber-js-git-21813647'...
npm ERR! git clone --template=C:\Users\sg0951798\AppData\Roaming\npm-cache\_git-
remotes\_templates --mirror https://github.com/xolvio/cucumber-js.git C:\Users\s
g0951798\AppData\Roaming\npm-cache\_git-remotes\https-github-com-xolvio-cucumber
-js-git-21813647: fatal: unable to access 'https://github.com/xolvio/cucumber-js
.git/': Proxy CONNECT aborted
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:821:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child
_process.js:211:5)
npm WARN addRemoteGit  xolvio/cucumber-js#v0.9.4-chimp.2 resetting remote C:\Use
rs\sg0951798\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xolvio-cucumb
er-js-git-0166949a because of error: { [Error: Command failed: git -c core.longp
aths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
```

**Comment by samhatoum** [comment]
which version of npm are you using?

**Comment by mario-ortiz** [comment]
2.14.12 and Node 4.2.6

**Comment by mario-ortiz** [comment]
I'm starting to wonder if it was a Github problem, I tried to check the issue list in chimp to check one about a memory allocation problem in the JSON report, and I wasn't able to access github for maybe a couple of minutes, now its back again. Or maybe something wrong with the connection or Proxy here in the office.

**Comment by samhatoum** [comment]
quite possibly. Chimp links to dependencies in GitHub directly, that's what the error is showing. Can you try with a phone tether perhaps to isolate local network issues?

**Comment by mario-ortiz** [comment]
Yes Sam, it was a problem with Github at that particular moment. When I tried the first time I when to github and couldn't access the URL from Xolvio (but other pages were working fine), but a minute after, everything was working as expected.

**Comment by samhatoum** [comment]
Great, thanks!
