### ISSUE TITLE
Chimp error on calling server.execute(), error message: need to install xolvio:backdoor

### ISSUE THREAD

**Issue by stevenjmarsh** [xolvio/chimp#294]
* What component is this issue related to (eg The JSON report):
Using chimp for a cucumber end-to-end test, without velocity or any other testing related packages in project. Chimp generates an error on a scenario step that calls server.execute().
Project: https://github.com/stevenjmarsh/meteor-clock-chimp
Similar detail stated in README.md

* Expected behaviour 
Expected chimp to complete test gracefully.

* Actual behaviour:
Chimp threw an exception, logged an error message, when trying to execute server.execute().

* Steps to reproduce the problem (preferably a reproducable repository):
Repo:  https://github.com/stevenjmarsh/meteor-clock-chimp
meteor --settings settings.json
chimp --ddp=http://localhost:3000 --path=./tests/cucumber/features --browser=phantomjs'

* Version of Chimp, Node and Operating System:
Chimp v0.30.0
Node v4.3.0
Mac OS X v10.10.5

* Console / Log Output:
note, log output is also captured in repo in file 'chimp.log'
I'll also include a screen shot of a breakpoint in debugger where chimp exception is thrown.
```
[16:55:16][../meteor-clock-chimp]$ ccph --debug --log=verbose
[chimp] Chimp options are { watch: false,
  watchTags: '@dev,@watch,@focus',
  watchWithPolling: false,
  criticalSteps: null,
  criticalTag: '@critical',
  server: false,
  serverPort: 8060,
  serverHost: 'localhost',
  sync: true,
  offline: false,
  path: './features',
  format: 'pretty',
  tags: '~@ignore',
  singleSnippetPerFile: true,
  recommendedFilenameSeparator: '_',
  chai: false,
  screenshotsOnError: false,
  screenshotsPath: '.screenshots',
  captureAllStepScreenshots: true,
  saveScreenshotsToDisk: false,
  saveScreenshotsToReport: true,
  jsonOutput: null,
  compiler: 'js:/usr/local/lib/node_modules/chimp/dist/lib/babel-register.js',
  browser: 'chrome',
  platform: 'ANY',
  name: '',
  user: '',
  key: '',
  port: null,
  host: null,
  deviceName: null,
  baseUrl: null,
  timeoutsAsyncScript: 10000,
  timeoutsImplicitWait: 3000,
  waitForTimeout: 10000,
  chromeBin: null,
  chromeArgs: null,
  chromeNoSandbox: false,
  noSessionReuse: false,
  browserstackLocal: false,
  tunnelIdentifier: null,
  simianResultEndPoint: 'api.simian.io/v1.0/result',
  simianAccessToken: false,
  simianResultBranch: null,
  simianRepositoryId: null,
  mocha: false,
  mochaTimeout: 60000,
  mochaReporter: 'spec',
  mochaSlow: 10000,
  ddp: false,
  phantom_w: 1280,
  phantom_h: 1024,
  log: 'info',
  debug: false,
  seleniumDebug: null,
  webdriverLogLevel: null,
  debugCucumber: null,
  debugBrkCucumber: null,
  debugMocha: null,
  debugBrkMocha: null }

[chimp] Running...
[chimp] interrupting
[chimp] no processes to interrupt
[chimp][phantom] starting process
[chimp][phantom.stdout] PhantomJS is launching GhostDriver...

[chimp][phantom.stdout] [INFO  - 2016-02-25T21:55:54.220Z] GhostDriver - Main - running on port 64298

[chimp][phantom] started successfully
[chimp][cucumber] Cucumber exec options are:  [ 'node',
  '/usr/local/lib/node_modules/chimp/node_modules/.bin/cucumber.js',
  './tests/cucumber/features',
  '-r',
  '/usr/local/lib/node_modules/chimp/dist/lib/chimp-helper.js',
  '-r',
  '/usr/local/lib/node_modules/chimp/dist/lib/cucumberjs/world.js',
  '-r',
  '/usr/local/lib/node_modules/chimp/dist/lib/cucumberjs/hooks.js',
  '-r',
  './tests/cucumber/features',
  '--format',
  'pretty',
  '--tags',
  '~@ignore',
  '--compiler',
  'js:/usr/local/lib/node_modules/chimp/dist/lib/babel-register.js' ]
[chimp][cucumber] Running with [ 'node',
  '/usr/local/lib/node_modules/chimp/node_modules/.bin/cucumber.js',
  './tests/cucumber/features',
  '-r',
  '/usr/local/lib/node_modules/chimp/dist/lib/chimp-helper.js',
  '-r',
  '/usr/local/lib/node_modules/chimp/dist/lib/cucumberjs/world.js',
  '-r',
  '/usr/local/lib/node_modules/chimp/dist/lib/cucumberjs/hooks.js',
  '-r',
  './tests/cucumber/features',
  '--format',
  'pretty',
  '--tags',
  '~@ignore',
  '--compiler',
  'js:/usr/local/lib/node_modules/chimp/dist/lib/babel-register.js' ]
[chimp][ddp] creating DDP wrapper

[chimp][ddp] Connecting to DDP server { host: 'localhost',
  port: '3000',
  ssl: false,
  autoReconnect: true,
  autoReconnectTimer: 500,
  maintainCollections: true,
  ddpVersion: '1',
  useSockJs: true }

[chimp][helper] Using the jasmine-expect assertion library

[chimp][hooks] Starting BeforeFeatures

[chimp][helper] getting browser

[chimp][session-manager-factory] options are { host: 'localhost',
  port: '64298',
  user: '',
  key: '',
  browser: 'phantomjs',
  deviceName: 'null' }

[chimp][session-manager] options are { host: 'localhost',
  port: '64298',
  user: '',
  key: '',
  browser: 'phantomjs',
  deviceName: 'null' }

[chimp][session-manager] created a new SessionManager { host: 'localhost',
  port: '64298',
  user: '',
  key: '',
  browser: 'phantomjs',
  deviceName: 'null' }

[chimp][helper] custom chimp.js not found, loading defaults

[chimp][helper] webdriverOptions are  {"waitforTimeout":10000,"timeoutsImplicitWait":3000,"desiredCapabilities":{"browserName":"phantomjs","platform":"ANY","name":"","chromeOptions":{},"applicationCacheEnabled":false,"tunnelIdentifier":"null","browserstack.local":"false"},"host":"localhost","port":"64298","logLevel":"verbose","sync":true}

[chimp][session-manager] creating webdriver remote


=======================================================================================

Selenium 2.0/webdriver protocol bindings implementation with helper commands in nodejs.

For a complete list of commands, visit http://webdriver.io/docs.html.

=======================================================================================


[chimp][session-manager] checking connection to selenium server

[16:55:56]:  COMMAND    GET      "/wd/hub/status"

[16:55:56]:  DATA                {}

[16:55:56]:  RESULT              {"build":{"version":"1.1.0"},"os":{"name":"mac","version":"10.10 (Yosemite)","arch":"32bit"}}

[chimp][session-manager] Connection to the to selenium server verified

[chimp][session-manager] browser is phantomjs, not reusing a session

[chimp][helper] init browser

[16:55:56]:  COMMAND    POST     "/wd/hub/session"

[16:55:56]:  DATA                {"desiredCapabilities":{"browserName":"phantomjs","javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"platform":"ANY","name":"","chromeOptions":{},"applicationCacheEnabled":false,"tunnelIdentifier":"null","browserstack.local":"false","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"3.4.0","name":"webdriverio"}}}

[chimp][phantom.stdout] [INFO  - 2016-02-25T21:55:56.572Z] Session [8c42f450-dc0a-11e5-9ec9-b7a01d66f723] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34","webSecurityEnabled":true}
[INFO  - 2016-02-25T21:55:56.572Z] Session [8c42f450-dc0a-11e5-9ec9-b7a01d66f723] - page.customHeaders:  - {}

[chimp][phantom.stdout] [INFO  - 2016-02-25T21:55:56.572Z] Session [8c42f450-dc0a-11e5-9ec9-b7a01d66f723] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"1.9.8","driverName":"ghostdriver","driverVersion":"1.1.0","platform":"mac-10.10 (Yosemite)-32bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2016-02-25T21:55:56.572Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 8c42f450-dc0a-11e5-9ec9-b7a01d66f723

[16:55:56]:  SET SESSION ID 8c42f450-dc0a-11e5-9ec9-b7a01d66f723

[16:55:56]:  RESULT              {"browserName":"phantomjs","version":"1.9.8","driverName":"ghostdriver","driverVersion":"1.1.0","platform":"mac-10.10 (Yosemite)-32bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}

[chimp][helper] init browser callback

[16:55:56]:  COMMAND    POST     "/wd/hub/session/8c42f450-dc0a-11e5-9ec9-b7a01d66f723/timeouts/async_script"

[16:55:56]:  DATA                {"ms":10000}

[16:55:56]:  RESULT              {}

[chimp][helper] set timeoutsAsyncScript

[16:55:56]:  COMMAND    GET      "/wd/hub/session/8c42f450-dc0a-11e5-9ec9-b7a01d66f723/window/current/size"

[16:55:56]:  DATA                {}

[16:55:56]:  RESULT              {"height":300,"width":400}

[16:55:56]:  COMMAND    POST     "/wd/hub/session/8c42f450-dc0a-11e5-9ec9-b7a01d66f723/execute"

[16:55:56]:  DATA                {"script":"return (function () {\n    return {\n        screenWidth: Math.max(document.documentElement.clientWidth, window.innerWidth || 0),\n        screenHeight: Math.max(document.documentElement.clientHeight, window.innerHeight || 0)\n    };\n}).apply(null, arguments);","args":[]}

[16:55:56]:  RESULT              {"screenWidth":400,"screenHeight":300}

[16:55:56]:  COMMAND    POST     "/wd/hub/session/8c42f450-dc0a-11e5-9ec9-b7a01d66f723/window/current/size"

[16:55:56]:  DATA                {"width":1280,"height":1024}

[16:55:56]:  RESULT              {}

[16:55:56]:  COMMAND    POST     "/wd/hub/session/8c42f450-dc0a-11e5-9ec9-b7a01d66f723/execute"

[16:55:56]:  DATA                {"script":"return (function () {\n    return {\n        screenWidth: Math.max(document.documentElement.clientWidth, window.innerWidth || 0),\n        screenHeight: Math.max(document.documentElement.clientHeight, window.innerHeight || 0)\n    };\n}).apply(null, arguments);","args":[]}

[16:55:56]:  RESULT              {"screenWidth":1280,"screenHeight":1024}

[chimp][helper] setup DDP

[chimp][helper] connecting via DDP to http://localhost:3000

[chimp][helper] connecting via DDP had no error

[chimp][hooks] Finished BeforeFeatures

[chimp][hooks] User-defined BeforeFeatures not found, finishing up

Feature: Curate a meaningful readable landing page


  As an author
  I want to curate a landing page with a meaningful layout
  So it is easy to read and understand


  Scenario: Author the heading_execute                         # tests/cucumber/features/landing_page.feature:15

    Given I have created a landing page with a heading_execute # tests/cucumber/features/landing_page.js:13

      Error: [chimp] You need to install xolvio:backdoor in your meteor app before you can use server.execute()
          at Object.global.ddp.execute (/usr/local/lib/node_modules/chimp/dist/lib/chimp-helper.js:184:19)
          at World.<anonymous> (landing_page.js:17:41)
          at /usr/local/lib/node_modules/chimp/node_modules/meteor-promise/fiber_pool.js:33:40

    When a user navigates to my page                           # tests/cucumber/features/landing_page.js:24

    Then they can see the heading                              # tests/cucumber/features/landing_page.js:28



[chimp][cucumber] Received message from cucumber child. Result: [
  {
    "id": "Curate-a-meaningful-readable-landing-page",
    "name": "Curate a meaningful readable landing page",
    "description": "\nAs an author\nI want to curate a landing page with a meaningful layout\nSo it is easy to read and understand",
    "line": 1,
    "keyword": "Feature",
    "uri": "/Users/smarsh/Dropbox/dev/practice/meteor/testing/meteor-clock-chimp/tests/cucumber/features/landing_page.feature",
    "elements": [
      {
        "name": "Author the heading_execute",
        "id": "Curate-a-meaningful-readable-landing-page;author-the-heading_execute",
        "line": 15,
        "keyword": "Scenario",
        "description": "",
        "type": "scenario",
        "steps": [
          {
            "name": "I have created a landing page with a heading_execute",
            "line": 16,
            "keyword": "Given ",
            "result": {
              "status": "failed",
              "duration": 19016092,
              "error_message": "Error: [chimp] You need to install xolvio:backdoor in your meteor app before you can use server.execute()\n    at Object.global.ddp.execute (/usr/local/lib/node_modules/chimp/dist/lib/chimp-helper.js:184:19)\n    at World.<anonymous> (landing_page.js:17:41)\n    at /usr/local/lib/node_modules/chimp/node_modules/meteor-promise/fiber_pool.js:33:40"
            },
            "match": {}
          },
          {
            "name": "a user navigates to my page",
            "line": 17,
            "keyword": "When ",
            "result": {
              "status": "skipped"
            },
            "match": {}
          },
          {
            "name": "they can see the heading",
            "line": 18,
            "keyword": "Then ",
            "result": {
              "status": "skipped"
            },
            "match": {}
          },
          {
            "keyword": "After ",
            "hidden": true,
            "result": {
              "status": "passed",
              "duration": 1245254
            },
            "match": {}
          }
        ]
      }
    ]
  }
]
Failing scenarios:
tests/cucumber/features/landing_page.feature:15 # Scenario: Author the heading_execute

1 scenario (1 failed)
3 steps (1 failed, 2 skipped)
0m00.021s
[chimp][hooks] Starting AfterFeatures
[chimp][hooks] Finished AfterFeatures

[chimp][cucumber] Closed with code 2
[chimp][cucumber] Cucumber not in a stopping state
[chimp] Finished running async processes with errors
[chimp] run complete with errors Cucumber steps failed
Cucumber steps failed
Error in chimp init Cucumber steps failed
```

Debugger Screen Shot:
![screen shot 2016-02-25 at 4 43 35 pm](https://cloud.githubusercontent.com/assets/6202447/13336535/7723b170-dbe4-11e5-879f-ad7cf5ae7390.png)

**Comment by stevenjmarsh** [comment]
I suspect this is not a defect, but instead missing a package that should have been installed by a user (in this case me). I'll review any documented steps to see what I may have missed. (If I find something, I will point out whether: I missed a documented step [my error], a necessary step was not documented, or a documented step was unclear to me)

**Comment by samhatoum** [comment]
you just need to write 

`meteor add xolvio:backdoor`

and it should work :)

**Comment by stevenjmarsh** [comment]
Thanks, I believe I tried that, and something went wrong. I will try again and note any unsuccessful responses.

**Comment by stevenjmarsh** [comment]
Thanks, I went back and spotted in the chimp.readme.io docs (getting started with meteor cucumber), the step stating you need to install backdoor. Missing that was my mistake (and the error message is pretty clear :) ).

When adding backdoor however, I am getting an application error (application is crashing).
Install xolvio:backdoor error (crashes app):

.../.meteor/local/build/programs/server/boot.js:283 }).run(); ^ TypeError: Object [object Object] has no method 'methods' at Package (server.js:3:8) ...

This is still probably steps that I am missing, and I am willing to close this issue, once I try a couple more things. Thanks for following up.

On a sidenote, does 1.3 remove the need to install backdoor, providing some other mechanism for server method calls?

**Comment by Sanjo** [comment]
With what Meteor version do you get this error? It seems xolvio:backdoor needs to depend on the Meteor package that exposes Meteor.methods.

In 1.3 this package will still be necessary.

**Comment by stevenjmarsh** [comment]
I am running this with Meteor 1.2.1

I installed each of the dependent / dependency packages manually listed per atmosphere for xolvio:backdoor (ecmascript, check, meteor, & quadric:backdoor-raw). meteor-base is installed. I even added back insecure. I have not been able to determine what other package would be needed to expose Meteor.methods for backdoor. I am able to successfully call a method from the client (Meteor.call('logServerMessage', 'log this');)

**Comment by stevenjmarsh** [comment]
Regardless of the issues I did run in to, none were for Chimp. I am closing this issue. And will try using xolvio:backdoor again in a different test app. If I have any issues with that, will open a separate issue there. thanks.
