### ISSUE TITLE
[chimp][helper] setupBrowserAndDDP had error

### ISSUE THREAD

**Issue by RavDanny** [xolvio/chimp#297]
Hi,

I just installed Chimp on my Ubuntu VM.
When I ran `chimp --watch` it gave the message:
`[chimp][helper] setupBrowserAndDDP had error`

I don't have any Xterm or window system set up on the VM. I wasn't sure if that was needed to be done by me to set up a browser or if Chimp does it itself.

* Version of Chimp, Node and Operating System:
Chimp v.0.9.4
Node v.4.3.1
Ubuntu 14.04 LTS running on Virtualbox VM

* Console / Log Output:
```
danny@danny-ubuntu:~/chimp-tutorial$ chimp --watch --debug
[chimp] Chimp options are { watch: false,
  watchTags: '@dev,@watch,@focus',
  watchWithPolling: false,
  criticalSteps: null,
  criticalTag: '@critical',
  server: false,
  serverPort: 8060,
  serverHost: 'localhost',
  sync: true,
  offline: false,
  path: './features',
  format: 'pretty',
  tags: '~@ignore',
  singleSnippetPerFile: true,
  recommendedFilenameSeparator: '_',
  chai: false,
  screenshotsOnError: false,
  screenshotsPath: '.screenshots',
  captureAllStepScreenshots: true,
  saveScreenshotsToDisk: false,
  saveScreenshotsToReport: true,
  jsonOutput: null,
  compiler: 'js:/usr/lib/node_modules/chimp/dist/lib/babel-register.js',
  browser: 'chrome',
  platform: 'ANY',
  name: '',
  user: '',
  key: '',
  port: null,
  host: null,
  deviceName: null,
  baseUrl: null,
  timeoutsAsyncScript: 10000,
  timeoutsImplicitWait: 3000,
  waitForTimeout: 10000,
  chromeBin: null,
  chromeArgs: null,
  chromeNoSandbox: false,
  noSessionReuse: false,
  browserstackLocal: false,
  tunnelIdentifier: null,
  simianResultEndPoint: 'api.simian.io/v1.0/result',
  simianAccessToken: false,
  simianResultBranch: null,
  simianRepositoryId: null,
  mocha: false,
  mochaTimeout: 60000,
  mochaReporter: 'spec',
  mochaSlow: 10000,
  ddp: false,
  phantom_w: 1280,
  phantom_h: 1024,
  log: 'info',
  debug: false,
  seleniumDebug: null,
  webdriverLogLevel: null,
  debugCucumber: null,
  debugBrkCucumber: null,
  debugMocha: null,
  debugBrkMocha: null }
[chimp] Watching features with tagged with @dev,@watch,@focus
[chimp] watcher ready, running for the first time
[chimp] rerunning

[chimp] Running...
[chimp] interrupting
[chimp] no processes to interrupt
[chimp][selenium] Selenium object created
[chimp][selenium] Start
[chimp][selenium] Installing Selenium + drivers if needed

[chimp][selenium] hub can be seen at http://localhost:49661/wd/hub
[chimp][session-manager] options are { host: 'localhost',
  port: '49661',
  browser: 'chrome',
  deviceName: 'null' }
[chimp][session-manager] created a new SessionManager { host: 'localhost',
  port: '49661',
  browser: 'chrome',
  deviceName: 'null' }
[chimp][cucumber] Cucumber exec options are:  [ 'node',
  '/usr/lib/node_modules/chimp/node_modules/.bin/cucumber.js',
  './features',
  '-r',
  '/usr/lib/node_modules/chimp/dist/lib/chimp-helper.js',
  '-r',
  '/usr/lib/node_modules/chimp/dist/lib/cucumberjs/world.js',
  '-r',
  '/usr/lib/node_modules/chimp/dist/lib/cucumberjs/hooks.js',
  '-r',
  './features',
  '--format',
  'pretty',
  '--tags',
  '@dev,@watch,@focus',
  '--compiler',
  'js:/usr/lib/node_modules/chimp/dist/lib/babel-register.js' ]
[chimp][cucumber] Running with [ 'node',
  '/usr/lib/node_modules/chimp/node_modules/.bin/cucumber.js',
  './features',
  '-r',
  '/usr/lib/node_modules/chimp/dist/lib/chimp-helper.js',
  '-r',
  '/usr/lib/node_modules/chimp/dist/lib/cucumberjs/world.js',
  '-r',
  '/usr/lib/node_modules/chimp/dist/lib/cucumberjs/hooks.js',
  '-r',
  './features',
  '--format',
  'pretty',
  '--tags',
  '@dev,@watch,@focus',
  '--compiler',
  'js:/usr/lib/node_modules/chimp/dist/lib/babel-register.js' ]
[chimp][helper] Using the jasmine-expect assertion library

[chimp][hooks] Starting BeforeFeatures

[chimp][helper] getting browser

[chimp][session-manager-factory] options are { host: 'localhost',
  port: '49661',
  user: '',
  key: '',
  browser: 'chrome',
  deviceName: 'null' }

[chimp][session-manager] options are { host: 'localhost',
  port: '49661',
  user: '',
  key: '',
  browser: 'chrome',
  deviceName: 'null' }

[chimp][session-manager] created a new SessionManager { host: 'localhost',
  port: '49661',
  user: '',
  key: '',
  browser: 'chrome',
  deviceName: 'null' }

[chimp][helper] custom chimp.js not found, loading defaults

[chimp][helper] webdriverOptions are  {"waitforTimeout":10000,"timeoutsImplicitWait":3000,"desiredCapabilities":{"browserName":"chrome","platform":"ANY","name":"","chromeOptions":{},"applicationCacheEnabled":false,"tunnelIdentifier":"null","browserstack.local":"false"},"host":"localhost","port":"49661","logLevel":"silent","sync":true}

[chimp][session-manager] creating webdriver remote

[chimp][session-manager] checking connection to selenium server

[chimp][session-manager] Connection to the to selenium server verified

[chimp][session-manager] requesting sessions from http://localhost:49661/wd/hub/sessions

[chimp][session-manager] received data {"state":"success","sessionId":null,"hCode":85524990,"value":[],"class":"org.openqa.selenium.remote.Response","status":0}

[chimp][session-manager] Did not find any open selenium sessions, not reusing a session

[chimp][session-manager] monkey patching the browser object

[chimp][helper] init browser

[chimp][session-manager] initializing browser

[chimp][helper] setupBrowserAndDDP had error
{ [Error: An unknown server-side error occurred while processing the command. (UnknownError:13)]
  message: 'An unknown server-side error occurred while processing the command. (UnknownError:13)',
  type: 'RuntimeError' }
Error: An unknown server-side error occurred while processing the command. (UnknownError:13)
    at Object.Future.wait (/usr/lib/node_modules/chimp/node_modules/fibers/future.js:449:15)
    at Object.<anonymous> (/usr/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/xolvio-fiber-utils/index.js:48:19)
    at Object.<anonymous> (/usr/lib/node_modules/chimp/dist/lib/session-manager.js:135:21)
    at initBrowser (/usr/lib/node_modules/chimp/dist/lib/chimp-helper.js:151:15)
    at Object.setupBrowserAndDDP (/usr/lib/node_modules/chimp/dist/lib/chimp-helper.js:229:7)
    at /usr/lib/node_modules/chimp/dist/lib/cucumberjs/hooks.js:21:24
    at /usr/lib/node_modules/chimp/node_modules/cucumber/node_modules/meteor-promise/fiber_pool.js:33:40
    - - - - -
    at new ErrorHandler.RuntimeError (/usr/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/lib/utils/ErrorHandler.js:93:12)
    at RequestHandler.<anonymous> (/usr/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/lib/utils/RequestHandler.js:138:25)
    at Request.self.callback (/usr/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/request/request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/request/request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/request/request.js:1266:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)
[chimp][cucumber] Closed with code 2
[chimp][cucumber] Cucumber not in a stopping state
[chimp] Finished running async processes with errors
[chimp] run complete with errors Cucumber steps failed
[chimp] finished rerun
```

**Comment by raddevon** [comment]
@RavDanny Were you able to fix this? Having a similar problem.

**Comment by RavDanny** [comment]
No, I didn't. I assumed it was because I didn't have Xterm set up. I didn't
end up using Chimp, so I never pursued it.
Good luck.

**Comment by samhatoum** [comment]
if you don't have xterm, you need to use Xvfb. Let me know if you need help with that @raddevon

**Comment by raddevon** [comment]
I would love some help, @samhatoum. I've tried to set it up using Xfvb and had no luck. I'm trying to get Chimp tests to work inside an Ubuntu Vagrant VM.

**Comment by raddevon** [comment]
Is this offer for help still open, @samhatoum? If so, how can we get together? I'd love to get Chimp working inside Vagrant.

**Comment by samhatoum** [comment]
yes. join our [xolv.io/community](http://xolv.io/community) and we can chat there
