### ISSUE TITLE
Using cucumber fail-fast option causes crash

### ISSUE THREAD

**Issue by dane-harnett** [xolvio/chimp#327]
* What component is this issue related to (eg The JSON report): Cucumber fail fast/Running tests

* Expected behaviour: Tests execute and abort on first failure

* Actual behaviour: No tests execute and a crash report is displayed

* Steps to reproduce the problem (preferably a reproducable repository):
```
$ chimp --baseUrl=https://mysite.com --browser=chrome --host=10.0.2.2 --port=4444 --fail-fast
```
* Version of Chimp, Node and Operating System:
Chimp 0.33.0
node -v    v5.8.0

* Console / Log Output:
```
[chimp] Running...
fs.js:887
  return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat '/data/prodigy/web/true'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at Object.realpathSync (fs.js:1518:21)
    at Object.expandPathWithExtensions (/data/prodigy/web/node_modules/cucumber/lib/cucumber/cli/path_expander.js:14:23)
    at /data/prodigy/web/node_modules/cucumber/lib/cucumber/cli/path_expander.js:8:27
    at Array.map (native)
    at Object.expandPathsWithExtensions (/data/prodigy/web/node_modules/cucumber/lib/cucumber/cli/path_expander.js:7:31)
    at Object.expandPaths (/data/prodigy/web/node_modules/cucumber/lib/cucumber/cli/feature_path_expander.js:9:38)
    at Function.Configuration (/data/prodigy/web/node_modules/cucumber/lib/cucumber/cli/configuration.js:20:63)
    at getConfiguration (/data/prodigy/web/node_modules/chimp/dist/lib/cucumberjs/cucumber-wrapper.js:47:38)
Cucumber steps failed
```

**Comment by dane-harnett** [comment]
for reference i was able to work around the issue by passing the features folder directly like so:
```
$ chimp --baseUrl=https://mysite.com --browser=chrome --host=10.0.2.2 --port=4444 --fail-fast ./features/
```

**Comment by samhatoum** [comment]
thanks for reporting back

**Comment by pscheit** [comment]
this is a bug, isnt it?

```
chimp tests/js/chimp/chimp.js --backtrace
```

should this work? (fails with the errors above). Even if i put "backtrace: true" into the chimp config it doesn't work

**Comment by samhatoum** [comment]
@pscheit I'm not sure what you mean. Could you open a new bug report please?

**Comment by pscheit** [comment]
how do I pass parameters to the command line runner from cucumber?

**Comment by samhatoum** [comment]
@pscheit I don't understand the question. Which command line runner? Cucumber doesn't really have access to a command line runner. 

Also, please open a new issue and be sure to follow the guidelines for reporting new issues. It's hard for me to help without the full context.
