### ISSUE TITLE
chimp not starting with node 6.0.0

### ISSUE THREAD

**Issue by preexo** [xolvio/chimp#349]
# NOTE FROM THE CHIMP TEAM

Given our very limited resources, we are reaching out to the community to support us. 

To expadite the development of this feature, we would love the financial help. We have recently joined the OpenCollective, an initiative that helps fund open source projects. We can move this ticket to the top of our pile if we can get it funded.

[Please pledge towards our goal by clicking here](https://goo.gl/czy4yc).

### $0 / $400 so far.

Thank you in advance!

-----

*Original post below:*

-----

#####  Expected behaviour
Chimp running smooth as always :)

#####  Actual behaviour
Chimp crashes at startup with the output below on my ubuntu and node 6.0.0

##### Steps to reproduce the problem
```
sudo chimp --ddp=http://localhost:3000 --watch --path=tests --browser=phantomjs
```
To avoid this issue I downgraded node back to 5.11.0, then everything works fine.
#####  Used version

* Chimp: 0.33.1
* Node.js: 6.0.0
* Operation system: Ubuntu 

#####  Console / Log Output

```
/usr/local/lib/node_modules/chimp/node_modules/fibers/fibers.js:16
	throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibers`?');
	^

Error: `/usr/local/lib/node_modules/chimp/node_modules/fibers/bin/linux-x64-v8-5.0/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/usr/local/lib/node_modules/chimp/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/index.js:8:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
```

**Comment by Sanjo** [comment]
Probably we need to wait for a new release of fibers, that has a binary for node 6.

**Comment by preexo** [comment]
Yeah, looks like it, not sure if a ticket in the fibers repro is necessary then.
Anyway, downgrading with `sudo n 5.11.0` solves all the issues, so no major problem at all :)

**Comment by ChrisOelmueller** [comment]
Is this issue being worked on? As I understand, Node 5 won't be supported for much longer, and Node 4 is a bit too old for me to downgrade to it.

**Comment by jsdtaylor** [comment]
+1

**Comment by hablijack** [comment]
+1

**Comment by kyv** [comment]
+1

**Comment by samhatoum** [comment]
[open PR here](https://github.com/xolvio/chimp/pull/393)

**Comment by samhatoum** [comment]
tracking in #393
