### ISSUE TITLE
Error running chimp after v0.34.1 install

### ISSUE THREAD

**Issue by brucejo75** [xolvio/chimp#361]
Started seeing this error after upgrading to 0.34.1, downgrading chimp does not fix it, so I think my `npm upgrade` pulled in a dependency that has an issue.
##### Expected behaviour

ran my tests with `chimp --ddp=http://localhost:3000 --mocha --chai --path=tests` will run the tests in my tests directory.
##### Actual behaviour

None of the tests start up, succeed or fail.  Only refers to the `"before all"` hook.  But I do not have a `before all hook` or any hook at all.
##### Steps to reproduce the problem

Will verify this is busted on a simple test repository (pressed for time right now).
##### Used version
- Chimp: 0.34.1, 0.34.0, 0.33.1
- Node.js: v5.8.0
- Operation system: Windows 10
##### Console / Log Output

```
(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at [object Object].addListener (events.js:252:17)
    at [object Object].once (events.js:278:8)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\chimp\node_modules\xolvio-ddp\lib\ddp-client.js:342:10
    at tryCatcher (C:\Users\admin\AppData\Roaming\npm\node_modules\chimp\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._resolveFromResolver (C:\Users\admin\AppData\Roaming\npm\node_modules\chimp\node_modules\bluebird\js\main\promise.js:480:31)
    at new Promise (C:\Users\admin\AppData\Roaming\npm\node_modules\chimp\node_modules\bluebird\js\main\promise.js:70:37)
    at [object Object].DDPClient.connect (C:\Users\admin\AppData\Roaming\npm\node_modules\chimp\node_modules\xolvio-ddp\lib\ddp-client.js:310:10)
    at [object Object]._onTimeout (C:\Users\admin\AppData\Roaming\npm\node_modules\chimp\node_modules\xolvio-ddp\lib\ddp-client.js:114:58)
    at Timer.listOnTimeout (timers.js:92:15)
(node) warning: possible EventEmitter memory leak detected. 11 failed listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at [object Object].addListener (events.js:252:17)
    at [object Object].once (events.js:278:8)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\chimp\node_modules\xolvio-ddp\lib\ddp-client.js:343:10
    at tryCatcher (C:\Users\admin\AppData\Roaming\npm\node_modules\chimp\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._resolveFromResolver (C:\Users\admin\AppData\Roaming\npm\node_modules\chimp\node_modules\bluebird\js\main\promise.js:480:31)
    at new Promise (C:\Users\admin\AppData\Roaming\npm\node_modules\chimp\node_modules\bluebird\js\main\promise.js:70:37)
    at [object Object].DDPClient.connect (C:\Users\admin\AppData\Roaming\npm\node_modules\chimp\node_modules\xolvio-ddp\lib\ddp-client.js:310:10)
    at [object Object]._onTimeout (C:\Users\admin\AppData\Roaming\npm\node_modules\chimp\node_modules\xolvio-ddp\lib\ddp-client.js:114:58)
    at Timer.listOnTimeout (timers.js:92:15)
 1) "before all" hook

  0 passing (1m)
  1 failing

  1)  "before all" hook:
     Error: timeout of 60000ms exceeded. Ensure the done() callback is being called in this test.
      at [object Object].<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\chimp\node_modules\mocha\lib\runnable.js:189:19)
```

**Comment by Sanjo** [comment]
This error means that your Meteor app is not running. You need to make sure that the Meteor app is running, before you start Chimp.

**Comment by brucejo75** [comment]
yeah, not sure what was happening.  At the time I was running it, `meteor test` was up, I had not restarted it between chimp installs?

I reinstalled chimp and rebuilt my app, all is working now.  Sorry for my fire alarm.

**Comment by rolljee** [comment]
Can i reopen it as i get the same error while meteor is running on localhost:3000 ?

**Comment by brucejo75** [comment]
did you try reinstall / rebuild?

**Comment by rolljee** [comment]
Tested again on windows with a fresh install : it worked 
Well, weird but cool ! Thx
