### ISSUE TITLE
How to define support / helpers?

### ISSUE THREAD

**Issue by lorensr** [xolvio/chimp#366]
Would be helpful to have a section in the docs on how to do this. These are the two ways I've tried: 

### Adding to `global`
```js
// tests/mocha/helpers.js
before(function() {
  global.load = (path) => {
   browser.url(url.resolve(process.env.ROOT_URL, path));
 }
```
now I can call `load` inside an `it`, but not inside a `beforeEach` (perhaps due to #355). 

### Importing

Suggested by #339

```js
// tests/mocha/helpers.js
load = (path) => {
  browser.url(url.resolve(process.env.ROOT_URL, path));
}
export { load }

// tests/mocha/foo.js
import { load } from '/tests/mocha/helpers.js';
// also tried: import { load } from 'helpers.js'; 
```

I get this:

```
chimp] Running...
/usr/local/lib/node_modules/chimp/dist/lib/mocha/mocha-wrapper.js:50
  throw e;
  ^

Error: Cannot find module '/tests/mocha/helpers.js'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (admin-basics.js:2:1)
    at Module._compile (module.js:541:32)
    at loader (/usr/local/lib/node_modules/chimp/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/chimp/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/chimp/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/local/lib/node_modules/chimp/node_modules/mocha/lib/mocha.js:213:14)
```

**Comment by Sanjo** [comment]
Absolute module paths currently start from the root of your disk. Use a relative path instead. Like: `import { load } from './helpers.js';`
