### ISSUE TITLE
How to define fixtures in Meteor 1.3?

### ISSUE THREAD

**Issue by lorensr** [xolvio/chimp#367]
![image](https://cloud.githubusercontent.com/assets/251288/15060094/a8b75d20-12f5-11e6-9d91-e2c72b765a3b.png)
https://chimp.readme.io/docs/getting-started-with-meteor-cucumber

In `tests/mocha/fixtures.js`

```js
// this doesn't help: import { Meteor } from 'meteor/meteor'
Meteor.methods({
  'fixtures/resetMyApp': function() {

  }
});
```  

results in:

```
[chimp] Running...
/usr/local/lib/node_modules/chimp/dist/lib/mocha/mocha-wrapper.js:50
  throw e;
  ^

ReferenceError: Meteor is not defined
    at Object.<anonymous> (methods.js:1:1)
    at Module._compile (module.js:541:32)
    at loader (/usr/local/lib/node_modules/chimp/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/chimp/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/chimp/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/local/lib/node_modules/chimp/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/usr/local/lib/node_modules/chimp/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/chimp/dist/lib/mocha/mocha-wrapper.js:46:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
=> Your Meteor application has errors. Waiting for file change.
```

**Comment by Sanjo** [comment]
* The tests folder is ignored by Meteor
* Chimp does not run inside the Meteor app
* You need to put the fixtures file inside a location where Meteor will execute it. The best location is a Meteor package with the testOnly: true flag. A file with the prefix .app-tests.js also works when the file is not in the tests folder.
* Make sure to start Meteor like this for Chimp: http://guide.meteor.com/testing.html#creating-acceptance-test-data

Also see http://guide.meteor.com/testing.html#creating-integration-test-data

**Comment by lorensr** [comment]
Thanks a lot! I suggested docs changes via readme.io

**Comment by Sanjo** [comment]
Thanks.
