### ISSUE TITLE
Cannot run chimp on Windows

### ISSUE THREAD

**Issue by tomaszzar** [xolvio/chimp#413]
#####  Expected behaviour

Chimp tests are running as always ; )

#####  Actual behaviour

Tests are not running

##### Steps to reproduce the problem

cd tests 
chimp --ddp=http://localhost:3000

#####  Used version

* Chimp: 0.35.0
* Node.js: v5.2.0
* Operation system: Windows_NT 10.0.10586

#####  Console / Log Output

```
c:\work\todos\tests>chimp --ddp=http://localhost:3000
C:\Users\Tomek\AppData\Local\.meteor\packages\xolvio_cucumber\0.20.3_1\npm\node_modules\chimp\node_modules\fibers\fibers.js:16
        throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibers`?');
        ^

Error: `C:\Users\Tomek\AppData\Local\.meteor\packages\xolvio_cucumber\0.20.3_1\npm\node_modules\chimp\node_modules\fibers\bin\win32-x64-v8-4.6\fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (C:\Users\Tomek\AppData\Local\.meteor\packages\xolvio_cucumber\0.20.3_1\npm\node_modules\chimp\node_modules\fibers\fibers.js:16:8)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (C:\Users\Tomek\AppData\Local\.meteor\packages\xolvio_cucumber\0.20.3_1\npm\node_modules\chimp\node_modules\xolvio-sync-webdriverio\index.js:7:13)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (C:\Users\Tomek\AppData\Local\.meteor\packages\xolvio_cucumber\0.20.3_1\npm\node_modules\chimp\lib\session-manager.js:37:38)
    at Module._compile (module.js:399:26)

c:\work\todos\tests>
```

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by tomaszzar** [comment]
My system path was pointing to a wrong node_modules directory. After changing path variable, chimp runs ok : )

**Comment by samhatoum** [comment]
thanks for reporting back

**Comment by Godsmith** [comment]
Could you kindly elaborate on how you solved this? I'm getting the same error, and I'm not sure how to fix it. Neither npm install -g chimp or npm install chimp works.

**Comment by samhatoum** [comment]
@Godsmith what version of node / chimp are you using?

**Comment by Godsmith** [comment]
I was running an old meteor 1.2 project, upgrading to 1.4.1 made it work, once I installed chimp locally + downgraded to 0.34 as detailed in #432.

**Comment by samhatoum** [comment]
great
