### ISSUE TITLE
Strange error ``Error: unknown error: session deleted because of page crash``

### ISSUE THREAD

**Issue by thebarty** [xolvio/chimp#417]
Hi guys,

I don't know what happend, but I am running into problems with chimp throwing this error:

```
Uncaught unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  Error: unknown error: session deleted because of page crash
      at Object.Future.wait (/Users/comeonletsgo/.node/lib/node_modules/chimp/node_modules/fibers/future.js:449:15)
      at Object.<anonymous> (/Users/comeonletsgo/.node/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/wdio-sync/build/index.js:345:27)
      at Function.setInputFieldToValue (ui-crud.acceptance.test.js:1832:17)
      at Function.validateShownFilter (ui-crud.acceptance.test.js:1282:16)
      at Context.<anonymous> (contacts.acceptance.test.js:2089:16)
      at /Users/comeonletsgo/.node/lib/node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      - - - - -
  from unknown error: cannot determine loading status
  from tab crashed
      at new RuntimeError (/Users/comeonletsgo/.node/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:115:12)
      at Request._callback (/Users/comeonletsgo/.node/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/build/lib/utils/RequestHandler.js:246:32)
      at Request.self.callback (/Users/comeonletsgo/.node/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/request/request.js:373:22)
      at Request.<anonymous> (/Users/comeonletsgo/.node/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/request/request.js:1318:14)
      at IncomingMessage.<anonymous> (/Users/comeonletsgo/.node/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/request/request.js:1266:12)
      at endReadableNT (_stream_readable.js:893:12)
```

the line throwing this error is
```
browser.selectByValue(selector, value)
```

Any ideas whats going on?

**Comment by thebarty** [comment]
Hi guys,

ok - this error appears when your browser is hanging and webdriver can NOT access the element.

So go check your ``browser.pause()`` or ``browser.waitFor()`` timeouts, OR enhance your user-interface to react faster and not block.

Closed for future reference
