### ISSUE TITLE
Unhandled rejection: Cannot read property 'getFileName'

### ISSUE THREAD

**Issue by jimmyhoneycutt** [xolvio/chimp#450]
I have chimp running on both my local Mac as well as our CI server, which is ubuntu. On ubuntu, I am getting strange errors when the Cucumber step is failing. I don't see this abnormality on the Mac.

The Cucumber step will fail when an element is not found on the page (i.e. browser.waitForExist()). We have timeouts set for 10 seconds, so the step should fail after 10 seconds if an element is not found. However, on Ubuntu it appears there is an error that occurs after trying to log the real error, which is causing some function to timeout after 60 seconds. So instead of the step failing in 10 seconds, some underlying function times out after 60 seconds. The following appears in the logs:

[chimp] Detected an unhandledRejection:
[chimp] Detected an unhandledRejection:
[chimp][hooks] TypeError: Cannot read property 'getFileName' of undefined

#####  Used version

* Chimp: 0.40.4
* Node.js: 4.4.7
* Operation system: Ubuntu

#####  Console / Log Output
Given I login as admin
    And I navigate to the "manageRoles" page
[chimp] Detected an unhandledRejection:
[chimp] Detected an unhandledRejection:
[chimp][hooks] TypeError: **Cannot read property 'getFileName' of undefined**
    at isFrameInCucumber (/home/tadmin/.nvm/versions/node/v4.4.7/lib/node_modules/chimp/node_modules/cucumber/lib/cucumber/runtime/stack_trace_filter.js:9:23)
    at Array.<anonymous> (/home/tadmin/.nvm/versions/node/v4.4.7/lib/node_modules/chimp/node_modules/cucumber/lib/cucumber/runtime/stack_trace_filter.js:15:9)
    at TraceModifier._modify (/home/tadmin/.nvm/versions/node/v4.4.7/lib/node_modules/chimp/node_modules/stack-chain/stack-chain.js:44:32)
    at Function.prepareStackTrace (/home/tadmin/.nvm/versions/node/v4.4.7/lib/node_modules/chimp/node_modules/stack-chain/stack-chain.js:119:25)
    at trackRejection (/home/tadmin/.nvm/versions/node/v4.4.7/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/q/q.js:1066:32)
    at reject (/home/tadmin/.nvm/versions/node/v4.4.7/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/q/q.js:1131:5)
    at deferred.reject (/home/tadmin/.nvm/versions/node/v4.4.7/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/q/q.js:633:16)
    at run (/home/tadmin/.nvm/versions/node/v4.4.7/lib/node_modules/chimp/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /home/tadmin/.nvm/versions/node/v4.4.7/lib/node_modules/chimp/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/home/tadmin/.nvm/versions/node/v4.4.7/lib/node_modules/chimp/node_modules/babel-runtime/node_modules/core-js/library/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

Failures:

1) Scenario: Assign permissions to user role - features/admin-roles.feature:18
   Step: And I have entered "Test" into the "addRoleInput" input - features/admin-roles.feature:21
   Step Definition: Given_I_have_entered_#_into_the_#_input.js:4
   Message:
     **function timed out after 60000 milliseconds**

1 scenario (1 failed)
14 steps (1 failed, 11 skipped, 2 passed)

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by jimmyhoneycutt** [comment]
I found another issue that is already opened referencing this same problem. Sorry for the duplication.

https://github.com/xolvio/chimp/issues/441
