### ISSUE TITLE
Timeout when attempting connect to app via DDP

### ISSUE THREAD

**Issue by nathanathan** [xolvio/chimp#476]
##### Expected behaviour

Chimp connects to the app via ddp when a --ddp parameter is provided.
##### Actual behaviour

Chimp errors out after a timeout on the "[chimp][helper] connecting via DDP to http://localhost:13000" step.
##### Steps to reproduce the problem
1. Download the repository here at the linked commit: https://github.com/ecohealthalliance/eidr-connect/tree/bbee8adcbd0084070a2562422eb405c418e6b0da
2. Download docker
3. Run `docker build -t eidr-connect-test -f test.Dockerfile .`. Chimp will be invoked by the final `run-tests-docker.sh` script in the build process.
##### Used version
- Chimp: 0.40.7
- Node.js: 4.4.7 (I also tried 6.6.0)
- Operation system: Ubuntu 16.04
##### Console / Log Output

```
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
[chimp] Chimp options are { watch: false,
  watchTags: '@focus,@dev,@watch',
  watchWithPolling: false,
  criticalSteps: null,
  criticalTag: '@critical',
  server: false,
  serverPort: 8060,
  serverHost: 'localhost',
  sync: true,
  offline: false,
  path: './features',
  format: 'pretty',
  tags: '~@ignore',
  singleSnippetPerFile: true,
  recommendedFilenameSeparator: '_',
  chai: false,
  screenshotsOnError: false,
  screenshotsPath: '.screenshots',
  captureAllStepScreenshots: false,
  saveScreenshotsToDisk: true,
  saveScreenshotsToReport: false,
  jsonOutput: null,
  compiler: 'js:/eidr-connect/node_modules/chimp/dist/lib/babel-register.js',
  conditionOutput: true,
  browser: 'chrome',
  platform: 'ANY',
  name: '',
  user: '',
  key: '',
  port: null,
  host: null,
  webdriverio: 
   { desiredCapabilities: {},
     logLevel: 'silent',
     host: '127.0.0.1',
     port: 4444,
     path: '/wd/hub',
     baseUrl: null,
     coloredLogs: true,
     screenshotPath: null,
     waitforTimeout: 500,
     waitforInterval: 250 },
  seleniumStandaloneOptions: 
   { version: '2.53.1',
     baseURL: 'https://selenium-release.storage.googleapis.com',
     drivers: { chrome: [Object], ie: [Object] } },
  noSessionReuse: false,
  simianResultEndPoint: 'api.simian.io/v1.0/result',
  simianAccessToken: false,
  simianResultBranch: null,
  simianRepositoryId: null,
  mocha: false,
  mochaTags: '',
  mochaGrep: null,
  mochaTimeout: 60000,
  mochaReporter: 'spec',
  mochaSlow: 10000,
  jasmine: false,
  jasmineConfig: 
   { specDir: '.',
     specFiles: [ '**/*@(_spec|-spec|Spec).@(js|jsx)' ],
     helpers: [ 'support/**/*.@(js|jsx)' ],
     stopSpecOnExpectationFailure: false,
     random: false },
  jasmineReporterConfig: {},
  ddp: false,
  phantom_w: 1280,
  phantom_h: 1024,
  log: 'info',
  debug: false,
  seleniumDebug: null,
  debugCucumber: null,
  debugBrkCucumber: null,
  debugMocha: null,
  debugBrkMocha: null }

[chimp] Running...
[chimp] interrupting
[chimp] no processes to interrupt
[chimp][phantom] starting process
[chimp][phantom.stdout] [INFO  - 2016-09-21T11:33:43.935Z] GhostDriver - Main - running on port 32825

[chimp][phantom] started successfully
[chimp][cucumber] Cucumber exec options are:  [ 'node',
  '/eidr-connect/node_modules/chimp/node_modules/.bin/cucumber.js',
  'tests/',
  '-r',
  '/eidr-connect/node_modules/chimp/dist/lib/chimp-helper.js',
  '-r',
  '/eidr-connect/node_modules/chimp/dist/lib/cucumberjs/world.js',
  '-r',
  '/eidr-connect/node_modules/chimp/dist/lib/cucumberjs/hooks.js',
  '-r',
  'tests/',
  '--compiler',
  'coffee:coffee-script/register',
  '--format',
  'pretty',
  '--tags',
  '~@ignore' ]
[chimp][cucumber] Running with [ 'node',
  '/eidr-connect/node_modules/chimp/node_modules/.bin/cucumber.js',
  'tests/',
  '-r',
  '/eidr-connect/node_modules/chimp/dist/lib/chimp-helper.js',
  '-r',
  '/eidr-connect/node_modules/chimp/dist/lib/cucumberjs/world.js',
  '-r',
  '/eidr-connect/node_modules/chimp/dist/lib/cucumberjs/hooks.js',
  '-r',
  'tests/',
  '--compiler',
  'coffee:coffee-script/register',
  '--format',
  'pretty',
  '--tags',
  '~@ignore' ]
[chimp][ddp] creating DDP wrapper

[chimp][ddp] Connecting to DDP server { host: 'localhost',
  port: '13000',
  ssl: false,
  autoReconnect: true,
  autoReconnectTimer: 500,
  maintainCollections: true,
  ddpVersion: '1',
  useSockJs: true }

[chimp][helper] Using the jasmine-expect assertion library

[chimp][hooks] Starting BeforeFeatures

[chimp][helper] getting browser

[chimp][session-manager-factory] options are { host: 'localhost',
  port: 32825,
  user: undefined,
  key: undefined,
  browser: 'phantomjs',
  deviceName: undefined }
[chimp][session-manager] options are { host: 'localhost',
  port: 32825,
  user: undefined,
  key: undefined,
  browser: 'phantomjs',
  deviceName: undefined }
[chimp][session-manager] created a new SessionManager { host: 'localhost',
  port: 32825,
  user: undefined,
  key: undefined,
  browser: 'phantomjs',
  deviceName: undefined }
[chimp][helper] webdriverioOptions are  {"desiredCapabilities":{"browserName":"phantomjs","platform":"ANY","name":""},"logLevel":"verbose","host":"localhost","port":32825,"path":"/wd/hub","baseUrl":null,"coloredLogs":true,"screenshotPath":null,"waitforTimeout":500,"waitforInterval":250,"sync":true}

[chimp][session-manager] creating webdriver remote 


=======================================================================================
Selenium 2.0 / webdriver protocol bindings implementation with helper commands in nodejs.
For a complete list of commands, visit http://webdriver.io/api.html.
=======================================================================================


[chimp][session-manager] checking connection to selenium server

[11:33:45]  COMMAND     GET      "/wd/hub/status"

[11:33:45]  DATA                {}

[11:33:45]  RESULT              {"build":{"version":"1.2.0"},"os":{"name":"linux","version":"unknown","arch":"64bit"}}

[chimp][session-manager] Connection to the to selenium server verified

[chimp][session-manager] browser is phantomjs, not reusing a session

[chimp][hooks] init browser

[chimp][hooks] init browser callback

[11:33:45]  COMMAND     POST     "/wd/hub/session"

[11:33:45]  DATA                {"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"phantomjs","platform":"ANY","name":"","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.2.16","name":"webdriverio"}}}

[chimp][phantom.stdout] [INFO  - 2016-09-21T11:33:45.681Z] Session [41a73fd0-7fef-11e6-bafa-093b36bd9535] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1","webSecurityEnabled":true}

[chimp][phantom.stdout] [INFO  - 2016-09-21T11:33:45.682Z] Session [41a73fd0-7fef-11e6-bafa-093b36bd9535] - page.customHeaders:  - {}

[chimp][phantom.stdout] [INFO  - 2016-09-21T11:33:45.682Z] Session [41a73fd0-7fef-11e6-bafa-093b36bd9535] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}

[chimp][phantom.stdout] [INFO  - 2016-09-21T11:33:45.685Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 41a73fd0-7fef-11e6-bafa-093b36bd9535

[11:33:45]  INFO        SET SESSION ID 41a73fd0-7fef-11e6-bafa-093b36bd9535

[11:33:45]  RESULT              {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}

[chimp][helper] init browser

[chimp][helper] init browser callback

[11:33:45]  COMMAND     GET      "/wd/hub/session/41a73fd0-7fef-11e6-bafa-093b36bd9535/window/current/size"
[11:33:45]  DATA                {}

[11:33:45]  RESULT              {"height":300,"width":400}

[11:33:45]  COMMAND     POST     "/wd/hub/session/41a73fd0-7fef-11e6-bafa-093b36bd9535/execute"

[11:33:45]  DATA                {"script":"return (function getViewportSize() {\n    return {\n        screenWidth: Math.max(document.documentElement.clientWidth, window.innerWidth || 0),\n        screenHeight: Math.max(document.documentElement.clientHeight, window.innerHeight || 0)\n    };\n}).apply(null, arguments)","args":[]}

[11:33:45]  RESULT              {"screenWidth":400,"screenHeight":300}

[11:33:45]  COMMAND     POST     "/wd/hub/session/41a73fd0-7fef-11e6-bafa-093b36bd9535/window/current/size"

[11:33:45]  DATA                {"width":1280,"height":1024}

[11:33:45]  RESULT              {}

[11:33:45]  COMMAND     POST     "/wd/hub/session/41a73fd0-7fef-11e6-bafa-093b36bd9535/execute"

[11:33:45]  DATA                {"script":"return (function getViewportSize() {\n    return {\n        screenWidth: Math.max(document.documentElement.clientWidth, window.innerWidth || 0),\n        screenHeight: Math.max(document.documentElement.clientHeight, window.innerHeight || 0)\n    };\n}).apply(null, arguments)","args":[]}

[11:33:45]  RESULT              {"screenWidth":1280,"screenHeight":1024}

[chimp][helper] setup DDP

[chimp][helper] connecting via DDP to http://localhost:13000

(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at [object Object].addListener (events.js:239:17)
  at [object Object].once (events.js:265:8)
  at /eidr-connect/node_modules/xolvio-ddp/lib/ddp-client.js:341:10
  at tryCatcher (/eidr-connect/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._resolveFromResolver (/eidr-connect/node_modules/bluebird/js/main/promise.js:483:31)
  at new Promise (/eidr-connect/node_modules/bluebird/js/main/promise.js:71:37)
  at [object Object].DDPClient.connect (/eidr-connect/node_modules/xolvio-ddp/lib/ddp-client.js:309:10)
  at [object Object]._onTimeout (/eidr-connect/node_modules/xolvio-ddp/lib/ddp-client.js:114:58)
  at Timer.listOnTimeout (timers.js:92:15)

(node) warning: possible EventEmitter memory leak detected. 11 failed listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at [object Object].addListener (events.js:239:17)
  at [object Object].once (events.js:265:8)
  at /eidr-connect/node_modules/xolvio-ddp/lib/ddp-client.js:342:10
  at tryCatcher (/eidr-connect/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._resolveFromResolver (/eidr-connect/node_modules/bluebird/js/main/promise.js:483:31)
  at new Promise (/eidr-connect/node_modules/bluebird/js/main/promise.js:71:37)
  at [object Object].DDPClient.connect (/eidr-connect/node_modules/xolvio-ddp/lib/ddp-client.js:309:10)
  at [object Object]._onTimeout (/eidr-connect/node_modules/xolvio-ddp/lib/ddp-client.js:114:58)
  at Timer.listOnTimeout (timers.js:92:15)


/eidr-connect/node_modules/chimp/node_modules/cucumber/lib/cucumber/runtime/event_broadcaster.js:30
            throw error;
            ^
node_modules/chimp/dist/lib/cucumberjs/hooks.js:19 function timed out after 60000 milliseconds
[chimp][cucumber] Closed with code 1
[chimp][cucumber] Cucumber not in a stopping state
[chimp] Finished running async processes with errors
[chimp] run complete with errors Cucumber steps failed
Cucumber steps failed
Error in chimp init Cucumber steps failed
```

---

_Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others._

**Comment by samhatoum** [comment]
This is likely due to docker not allowing a connection internally to http://localhost:13000

**Comment by nathanathan** [comment]
@samhatoum I tried execing into a container with that image, starting the app, then running `curl http://localhost:13000` and it returned the app's html, so it doesn't seem like internal connections to that port are being blocked by docker. Running the run-tests-docker.sh script from inside the container still returned the same error.

**Comment by samhatoum** [comment]
Can you try to run the example here against your app?

https://github.com/oortcloud/node-ddp-client

This is what we use. It might shed some light on the issue

**Comment by nathanathan** [comment]
Increasing the time for the app to start up before chimp starts running tests resolved the issue.

**Comment by samhatoum** [comment]
nice, thanks for reporting back
