### ISSUE TITLE
Jasmine test case with uncaught error passes

### ISSUE THREAD

**Issue by tiffon** [xolvio/chimp#480]
Brilliant work with Chimp, thanks for all the hard work!
## Expected behaviour

**Old way**: The error would be logged and the process would exit with an error. This is fine with me, quite handy for development, IMO.

**Ideal**: There is a config option to allow the process to crash, but by default Chimp fails the test case and moves on. Crashing the process is handy for development because the error is logged and the browser stays open in its last state.
## Actual behaviour

The test case passes with a green dot.
## Steps to reproduce the problem

File `chimp.config.js`:

```
module.exports = {
  path: 'tests',
  jasmine: true,
  browser: 'chrome'
};
```

File `tests/a-spec.js`:

```
describe('should have 1 pass and 2 fails', () => {

  it('should pass', () => {
    browser.url('http://www.google.com');
    expect(browser.getTitle()).toEqual('Google');
  });

  it('fails an expect', () => {
    browser.url('http://www.google.com');
    expect(browser.getTitle()).toEqual('something thats not google');
  });

  it('throws an Error', () => {
    throw new Error('this will not cause the test to fail');
  });
});

```

In a terminal:

```
$ npm install chimp && ./node_modules/.bin/chimp chimp.config.js
```
## Used version
- Chimp: 0.41.1
- Node.js: v4.4.6
- Operation system: OSX 10.11.6 
## Console / Log Output

Without `--debug`:

```
$ ./node_modules/.bin/chimp chimp.config.js

Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu


[chimp] Running...
selenium-standalone installation [====================] 100% 0.0sStarted
.F.

Failures:
1) should have 1 pass and 2 fails fails an expect
  Message:
    Expected 'Google' to equal 'something thats not google'.
  Stack:
    Error: Expected 'Google' to equal 'something thats not google'.
        at Object.<anonymous> (/[...]/chimp-uncaught-error/tests/a-spec.js:10:32)
        at /[...]/chimp-uncaught-error/node_modules/chimp/dist/lib/utils/fiberize.js:25:14

3 specs, 1 failure
Finished in 2.977 seconds

Jasmine failed
```

With `--debug`:

```
$ ./node_modules/.bin/chimp chimp.config.js --debug
[chimp] loaded /[...]/chimp-uncaught-error/chimp.config.js
[chimp] Chimp options are { watch: false,
  watchTags: '@watch,@focus',
  domainSteps: null,
  e2eSteps: null,
  fullDomain: false,
  domainOnly: false,
  e2eTags: '@e2e',
  watchWithPolling: false,
  server: false,
  serverPort: 8060,
  serverHost: 'localhost',
  sync: true,
  offline: false,
  showXolvioMessages: true,
  path: 'tests',
  format: 'pretty',
  tags: '~@ignore',
  singleSnippetPerFile: true,
  recommendedFilenameSeparator: '_',
  chai: false,
  screenshotsOnError: false,
  screenshotsPath: '.screenshots',
  captureAllStepScreenshots: false,
  saveScreenshotsToDisk: true,
  saveScreenshotsToReport: false,
  jsonOutput: null,
  compiler: 'js:/[...]/chimp-uncaught-error/node_modules/chimp/dist/lib/babel-register.js',
  conditionOutput: true,
  browser: 'chrome',
  platform: 'ANY',
  name: '',
  user: '',
  key: '',
  port: null,
  host: null,
  webdriverio:
   { desiredCapabilities: {},
     logLevel: 'silent',
     host: '127.0.0.1',
     port: 4444,
     path: '/wd/hub',
     baseUrl: null,
     coloredLogs: true,
     screenshotPath: null,
     waitforTimeout: 500,
     waitforInterval: 250 },
  seleniumStandaloneOptions:
   { version: '2.53.1',
     baseURL: 'https://selenium-release.storage.googleapis.com',
     drivers: { chrome: [Object], ie: [Object] } },
  noSessionReuse: false,
  simianResultEndPoint: 'api.simian.io/v1.0/result',
  simianAccessToken: false,
  simianResultBranch: null,
  simianRepositoryId: null,
  mocha: false,
  mochaTags: '',
  mochaGrep: null,
  mochaTimeout: 60000,
  mochaReporter: 'spec',
  mochaSlow: 10000,
  jasmine: true,
  jasmineConfig:
   { specDir: '.',
     specFiles: [ '**/*@(_spec|-spec|Spec).@(js|jsx)' ],
     helpers: [ 'support/**/*.@(js|jsx)' ],
     stopSpecOnExpectationFailure: false,
     random: false },
  jasmineReporterConfig: {},
  ddp: false,
  phantom_w: 1280,
  phantom_h: 1024,
  log: 'info',
  debug: false,
  seleniumDebug: null,
  debugCucumber: null,
  debugBrkCucumber: null,
  debugMocha: null,
  debugBrkMocha: null }

Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu


[chimp] Running...
[chimp] interrupting
[chimp] no processes to interrupt
[chimp][selenium] Selenium object created
[chimp][selenium] Start
[chimp][selenium] Installing Selenium + drivers if needed

[chimp][selenium] hub can be seen at http://localhost:57237/wd/hub
[chimp][session-manager] options are { host: 'localhost',
  port: '57237',
  browser: 'chrome',
  deviceName: undefined }
[chimp][session-manager] created a new SessionManager { host: 'localhost',
  port: '57237',
  browser: 'chrome',
  deviceName: undefined }
[chimp][jasmine] Running...
Started
[chimp][helper] getting browser
[chimp][session-manager-factory] options are { host: 'localhost',
  port: 57237,
  user: undefined,
  key: undefined,
  browser: 'chrome',
  deviceName: undefined }
[chimp][session-manager] options are { host: 'localhost',
  port: 57237,
  user: undefined,
  key: undefined,
  browser: 'chrome',
  deviceName: undefined }
[chimp][session-manager] created a new SessionManager { host: 'localhost',
  port: 57237,
  user: undefined,
  key: undefined,
  browser: 'chrome',
  deviceName: undefined }
[chimp][helper] webdriverioOptions are  {"desiredCapabilities":{"browserName":"chrome","platform":"ANY","name":""},"logLevel":"verbose","host":"localhost","port":57237,"path":"/wd/hub","baseUrl":null,"coloredLogs":true,"screenshotPath":null,"waitforTimeout":500,"waitforInterval":250,"sync":true}
[chimp][session-manager] creating webdriver remote

=======================================================================================
Selenium 2.0 / webdriver protocol bindings implementation with helper commands in nodejs.
For a complete list of commands, visit http://webdriver.io/api.html.
=======================================================================================

[chimp][session-manager] checking connection to selenium server
[01:02:35]  COMMAND GET      "/wd/hub/status"
[01:02:35]  DATA        {}
[01:02:35]  RESULT      {"build":{"version":"2.53.1","revision":"a36b8b1","time":"2016-06-30 17:37:03"},"os":{"name":"Mac OS X","arch":"x86_64","version":"10.11.6"},"java":{"version":"1.8.0_91"}}
[chimp][session-manager] Connection to the to selenium server verified
[chimp][session-manager] watch mode is false, not reusing a session
[chimp][hooks] init browser
[chimp][hooks] init browser callback
[01:02:35]  COMMAND POST     "/wd/hub/session"
[01:02:35]  DATA        {"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","platform":"ANY","name":"","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.2.16","name":"webdriverio"}}}
[01:02:36]  INFO    SET SESSION ID 97f6a33e-04f4-4b77-b318-d237262d8120
[01:02:36]  RESULT      {"applicationCacheEnabled":false,"rotatable":false,"mobileEmulationEnabled":false,"chrome":{"chromedriverVersion":"2.22.397929 (fb72fb249a903a0b1041ea71eb4c8b3fa0d9be5a)","userDataDir":"/var/folders/c0/5srb2p2j60b42h28b9dvd8nsh0q71c/T/.org.chromium.Chromium.obKcyL"},"takesHeapSnapshot":true,"databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":false,"version":"53.0.2785.116","platform":"MAC","browserConnectionEnabled":false,"nativeEvents":true,"acceptSslCerts":true,"webdriver.remote.sessionid":"97f6a33e-04f4-4b77-b318-d237262d8120","locationContextEnabled":true,"webStorageEnabled":true,"browserName":"chrome","takesScreenshot":true,"javascriptEnabled":true,"cssSelectorsEnabled":true}
[chimp][helper] init browser
[chimp][helper] init browser callback
[01:02:36]  COMMAND POST     "/wd/hub/session/97f6a33e-04f4-4b77-b318-d237262d8120/url"
[01:02:36]  DATA        {"url":"http://www.google.com"}
[01:02:37]  RESULT      null
[01:02:37]  COMMAND GET      "/wd/hub/session/97f6a33e-04f4-4b77-b318-d237262d8120/title"
[01:02:37]  DATA        {}
[01:02:37]  RESULT      "Google"
.[01:02:37]  COMMAND    POST     "/wd/hub/session/97f6a33e-04f4-4b77-b318-d237262d8120/url"
[01:02:37]  DATA        {"url":"http://www.google.com"}
[01:02:37]  RESULT      null
[01:02:37]  COMMAND GET      "/wd/hub/session/97f6a33e-04f4-4b77-b318-d237262d8120/title"
[01:02:37]  DATA        {}
[01:02:37]  RESULT      "Google"
F.[chimp][jasmine-helpers] Ending browser session
[chimp][session-manager] requesting sessions from http://localhost:57237/wd/hub/sessions
[chimp][session-manager] received data {"state":"success","sessionId":null,"hCode":1753408377,"value":[{"capabilities":{"applicationCacheEnabled":false,"rotatable":false,"mobileEmulationEnabled":false,"chrome":{"chromedriverVersion":"2.22.397929 (fb72fb249a903a0b1041ea71eb4c8b3fa0d9be5a)","userDataDir":"/var/folders/c0/5srb2p2j60b42h28b9dvd8nsh0q71c/T/.org.chromium.Chromium.obKcyL"},"takesHeapSnapshot":true,"databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":false,"version":"53.0.2785.116","platform":"MAC","browserConnectionEnabled":false,"nativeEvents":true,"acceptSslCerts":true,"locationContextEnabled":true,"webStorageEnabled":true,"browserName":"chrome","takesScreenshot":true,"javascriptEnabled":true,"cssSelectorsEnabled":true},"id":"97f6a33e-04f4-4b77-b318-d237262d8120","hCode":855456505,"class":"org.openqa.selenium.remote.server.handler.GetAllSessions$SessionInfo"}],"class":"org.openqa.selenium.remote.Response","status":0}
[chimp][session-manager] deleting wd session 97f6a33e-04f4-4b77-b318-d237262d8120
[chimp][session-manager] received data {"state":"success","sessionId":"97f6a33e-04f4-4b77-b318-d237262d8120","hCode":531885182,"value":null,"class":"org.openqa.selenium.remote.Response","status":0}
[chimp][jasmine-helpers] Ended browser sessions


Failures:
1) should have 1 pass and 2 fails fails an expect
  Message:
    Expected 'Google' to equal 'something thats not google'.
  Stack:
    Error: Expected 'Google' to equal 'something thats not google'.
        at Object.<anonymous> (/[...]/chimp-uncaught-error/tests/a-spec.js:10:32)
        at /[...]/chimp-uncaught-error/node_modules/chimp/dist/lib/utils/fiberize.js:25:14

3 specs, 1 failure
Finished in 2.71 seconds

[chimp][jasmine] Closed with code 1
[chimp][jasmine] Jasmine not in a stopping state
[chimp] Finished running async processes with errors
[chimp] run complete with errors Jasmine failed
Jasmine failed
Error in chimp init Jasmine failed
```

---

_Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others._

**Comment by tiffon** [comment]
Can the Chimp team comment on this.

Specifically, are test cases that throw exceptions passed, by design? Is that decision set in stone? Thanks.

**Comment by samhatoum** [comment]
Does this happen with standalone Jasmine?

**Comment by tiffon** [comment]
No it does not.

**Comment by gregorskii** [comment]
@samhatoum confirmed this is an issue on my end too. Using jasmine directly will fail on error. Adding a try/catch will expose the error with e.toString() in the catch(e).

**Comment by gregorskii** [comment]
@samhatoum if you remove the call to `fiberizeJasmineApi`  call in https://github.com/xolvio/chimp/blob/master/src/lib/jasmine/jasmine-wrapper.js#L35 the error is correctly reported to the console. However I do not know what impact this has on the plugins use of Fibers.

Per the current documentation of Fibers https://github.com/laverdet/node-fibers#api-documentation the call to:

```
function Fiber(fn) {
    [native code]
}
```

"When run() is called on this fiber for the first time, `fn` will be invoked as the first frame on a new stack. Execution will continue on this new stack until `fn` returns, or Fiber.yield() is called."

I don't think its returning or yeilding here:

https://github.com/xolvio/chimp/blob/master/src/lib/utils/fiberize.js#L6

Don't quite understand this part of the internals, but either way removing the call to Fibers results in the error being reported to the console. Likely some functionality in Fiberizing the call to Jasmine is resulting in the actual error response being ignored.

Adding this:

```
jasmine.onComplete((passed) => {
  console.log(arguments);
  if (passed) {
    console.log('All specs have passed');
  }
  else {
    console.log('At least one spec has failed');
  }
});
```

Above `jasmine.execute` here https://github.com/xolvio/chimp/blob/a9be09cb785cfee49ef319fdfec8d6d924fd9188/src/lib/jasmine/jasmine-wrapper.js#L41 results in the correct error message being reported in the chimp output and the test failing:

```
> @ watch-components PROJECT_PATH
> cross-env TESTING_MODE=components chimp chimp_component.js --watch


Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu

[chimp] Watching features with tagged with @watch,@focus

[chimp] Running...
Started
RUNNING
F

Failures:
1) test @watch
  Message:
    TypeError: cats.foo is not a function
  Stack:
    TypeError: cats.foo is not a function
        at Object.<anonymous> (PATH/main_spec.js:12:19)

Ran 1 of 117 specs
1 spec, 1 failure
Finished in 4.667 seconds

{}
At least one spec has failed
```

**Comment by gregorskii** [comment]
@samhatoum, did some digging into previous issues, reverting the changes on https://github.com/xolvio/chimp/pull/463 fixes this. Chimp throws the exception from within the Fiber, however the result does not propogate to Jasmine as a test failure it just throws an exception. Meaning the:

```
  jasmine.onComplete((passed) => {
    console.log(arguments);
    if (passed) {
      console.log('All specs have passed');
    }
    else {
      console.log('At least one spec has failed');
    }
  });
```

Never runs.
