### ISSUE TITLE
waitUntil does not log a useful stacktrace

### ISSUE THREAD

**Issue by acthp** [xolvio/chimp#484]
Before you ask, I've already opened an issue with webdriverio, who claim this is a chimp problem.

https://github.com/webdriverio/webdriverio/issues/1629

#####  Expected behaviour

An exception in a waitUntil condition should log the stacktrace of the error.

#####  Actual behaviour

A stacktrace into fiber / future code is logged.

##### Steps to reproduce the problem

Throw an error in a waitUntil condition.

#####  Used version

* Chimp:  0.41.1
* Node.js: 4.0.0
* Operation system: ubuntu

#####  Console / Log Output

     Error: Promise was rejected with the following reason: TypeError: undefined is not a function
      at Object.Future.wait (node_modules/fibers/future.js:449:15)
      at Object.<anonymous> (node_modules/wdio-sync/build/index.js:345:27)
      at Context.<anonymous> (test/chimp/test.js:110:12)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
 

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by lucetius** [comment]
Please provide us detailed steps to reproduce the error.

**Comment by lgandecki** [comment]
"Throw an error in a waitUntil condition."
I think this is enough for us to reproduce, thanks for submitting, we will take a look at this shortly!
