### ISSUE TITLE
server.execute throws "Can't wait without a Fiber"

### ISSUE THREAD

**Issue by thiagodelgado111** [xolvio/chimp#490]
#####  Expected behaviour
Runs code in Meteor context and the scenario passes

```
module.exports = function () {
  this.Given(/^something exists$/, async function () {
    const countThings = await this.countAllTheThings();

    server.execute(addRecord, 'text');

    function addRecord (text) {
      const MyCollection = require('meteor/mycollection');
      MyCollection.insert({ title: text });
    }
  });
};
```

#####  Actual behaviour

The scenario fails and an error message is logged on the console:

#####  Used version

* Chimp: 0.40.6
* Node.js: v5.5
* Operation system: 

ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1004

#####  Console / Log Output

```
Message:
     Error: Can't wait without a fiber
         at World._callee$ (features/step_definitions/common/Given_a_thing_is_counted.js:18:12)
         at nextTickCallbackWith0Args (node.js:452:9)
         at process._tickCallback (node.js:381:13)
```

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
Could you put this in a repro for us please? Difficult to see what's happening from just the code above
