### ISSUE TITLE
TypeError Cannot read property 'length' of undefined on Selenium Hub

### ISSUE THREAD

**Issue by jmatsushita** [xolvio/chimp#532]
#####  Expected behaviour

Session finishes without an error.

#####  Actual behaviour

```
TypeError: node_modules/chimp/dist/lib/cucumberjs/hooks.js:88 Cannot read property 'length' of undefined
    at .../code/microservices/tests/node_modules/chimp/dist/lib/session-manager.js:250:17
    at Request.<anonymous> (.../tests/node_modules/chimp/dist/lib/session-manager.js:216:7)
    at Request.f (.../tests/node_modules/fg-lodash/node_modules/lodash/dist/lodash.js:5605:23)
    at Request.<anonymous> (.../tests/node_modules/requestretry/index.js:57:17)
    at Request.self.callback (.../tests/node_modules/request/request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (.../tests/node_modules/request/request.js:1035:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (.../tests/node_modules/request/request.js:962:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

##### Exact steps to reproduce / repository that demonstrates the problem
Please put long code snips in a [Gist](https://gist.github.com/) and provide a link here.

I'm using the docker based selenium grid distribution.
https://gist.github.com/jmatsushita/6c69c8d42c540190c7cf8f15631f315f

Adding an [extra guard `sessions && ` in the condition on this line](https://github.com/xolvio/chimp/blob/master/src/lib/session-manager.js#L261) fixes it (i.e. the run finishes without errors).

#####  Version & tools:

* Chimp command line used:

./node_modules/.bin/chimp --offline --debug --host=seleniumhub.myhost.org --port=4444 --noSessionReuse

* Chimp config file: 

https://gist.github.com/jmatsushita/6c69c8d42c540190c7cf8f15631f315f

* Chimp: 0.43.0
* Node.js: v6.9.1
* Java: java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
* Operation system: Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64

#####  Console / Log Output

https://gist.github.com/jmatsushita/6c69c8d42c540190c7cf8f15631f315f

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by jmatsushita** [comment]
I still get the following error message with the guard:

```
[chimp][session-manager] received error null response IncomingMessage
```

I've added the complete error message to a new file on the same gist: https://gist.github.com/jmatsushita/6c69c8d42c540190c7cf8f15631f315f#file-chimp-log-after-session-null-guard

**Comment by samhatoum** [comment]
Thank you, accepted as a bug
