### ISSUE TITLE
Chimp throwing a "Error: unknown error: Chrome version must be >= 54.0.2840.0" on CircleCi. Any ideas how to solve this?

### ISSUE THREAD

**Issue by thebarty** [xolvio/chimp#557]
#####  Expected behaviour
On CircleCi Chimp should start und run against meteor without throwing an error

#####  Actual behaviour
With the listed `circle.yml` below Chimp throws an error ("Error: unknown error: Chrome version must be >= 54.0.2840.0") and does NOT run.

##### Exact steps to reproduce / repository that demonstrates the problem
This is the `circle.yml` I am using
```
# References
#  * https://forums.meteor.com/t/what-is-the-simplest-setup-for-meteor-chimp-on-circle-ci/31627
machine:
  node:
    version: 6.5.0
  java:
    # This is needed by Chimp to run Selenium so we can start Chrome and Firefox
    version: oraclejdk8
  environment:
    _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
    CIRCLE_ENV: circle  # for setting stuff in our .js files depending on environment
    MOCHA_FILE: $CIRCLE_TEST_REPORTS/junit/test-results.xml  # setup reporting for circle (see https://circleci.com/docs/test-metadata/#metadata-collection-in-custom-test-steps)

dependencies:
  pre:
    - pwd
    - google-chrome --version
    - cp src/.meteor/versions ${CIRCLE_ARTIFACTS}/versions_pre;
    - cd src; mkdir -p .meteor
    - if [ ! -e src/.meteor/meteor ]; then cd src; curl https://install.meteor.com | /bin/sh 2>&1 | cat; fi
    - pwd; cd src; pwd; meteor npm install;  # install npm-packages from ./src/packages.json
    - cd src; meteor --version;  # trying to cache and pre-heat meteor
    # - cd src; meteor --get-ready;  # currently FAILS, probably NOT enough memory
    - cd src; npm install -g chimp
    - cd src; chimp --path=noexist # Cache chimp deps by running it without any tests

  # Run METEOR IN PARALLEL
  post:
    - pwd
    # debug used versions
    - cp src/.meteor/versions ${CIRCLE_ARTIFACTS}/versions_post;
    - less src/.meteor/versions > ${CIRCLE_ARTIFACTS}/meteor.log;
    - date > ${CIRCLE_ARTIFACTS}/meteor.log
    - cd src; meteor test --full-app --driver-package tmeasday:acceptance-test-driver --port 3000 >> ${CIRCLE_ARTIFACTS}/meteor.log 2>&1 & :
        background: true

test:
  post:
    - pwd
    - ls -al
    - cd src; ls -al; node --version; npm --version; java -version; meteor --version;
    - sleep 5m  # give meteor-background some time to wake up
    - cd src; chimp ./tests/_circle-ci-chimp-config.js --ddp=http://localhost:3000 --path=tests --mocha;
```

#####  Version & tools:
This is happening on CircleCi. Locally my tests pass.

#####  Console / Log Output

This is the error log:
```
[chimp] Running...


[chimp][helper] setupBrowserAndDDP had error
{ Error: unknown error: Chrome version must be >= 54.0.2840.0
    at initBrowser (/opt/circleci/nodejs/v6.5.0/lib/node_modules/chimp/dist/lib/chimp-helper.js:174:17)
    at Object.setupBrowserAndDDP (/opt/circleci/nodejs/v6.5.0/lib/node_modules/chimp/dist/lib/chimp-helper.js:248:7)
    at Context.<anonymous> (/opt/circleci/nodejs/v6.5.0/lib/node_modules/chimp/dist/lib/mocha/mocha-helper.js:11:15)
    at /opt/circleci/nodejs/v6.5.0/lib/node_modules/chimp/dist/lib/utils/fiberize.js:25:14
    (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.13.0-106-generic x86_64)
  message: 'unknown error: Chrome version must be >= 54.0.2840.0\n  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.13.0-106-generic x86_64)',
  type: 'RuntimeError',
  seleniumStack: 
   { status: 13,
     type: 'UnknownError',
     message: 'An unknown server-side error occurred while processing the command.',
     orgStatusMessage: 'unknown error: Chrome version must be >= 54.0.2840.0\n  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.13.0-106-generic x86_64)' } }
Error: unknown error: Chrome version must be >= 54.0.2840.0
    at initBrowser (/opt/circleci/nodejs/v6.5.0/lib/node_modules/chimp/dist/lib/chimp-helper.js:174:17)
    at Object.setupBrowserAndDDP (/opt/circleci/nodejs/v6.5.0/lib/node_modules/chimp/dist/lib/chimp-helper.js:248:7)
    at Context.<anonymous> (/opt/circleci/nodejs/v6.5.0/lib/node_modules/chimp/dist/lib/mocha/mocha-helper.js:11:15)
    at /opt/circleci/nodejs/v6.5.0/lib/node_modules/chimp/dist/lib/utils/fiberize.js:25:14
    (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.13.0-106-generic x86_64)
Mocha failed

cd src; chimp ./tests/_circle-ci-chimp-config.js --ddp=http://localhost:3000 --path=tests --mocha; returned exit code 2
```

**Comment by yegortokmakov** [comment]
It happened due to an update of the underlying `chromedriver` to v2.7. 
You can fix it by updating Chrome on your machine to version >=54 or you can downgrade and fix version of Chromedriver (till CircleCI updates it's images).

To do this add `"chromedriver": "2.26.2"` in your `package.json` devDependencies.

Cheers

**Comment by samhatoum** [comment]
@thebarty you can add this to circle:
```
    # Update Chrome
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - sudo dpkg -i google-chrome-stable_current_amd64.deb
```

Only thing is it wont' be cached. You'd need to do some extra work for that, or just wait until circle update their chrome

**Comment by maxmckenzie** [comment]
@samhatoum how come this was reopened and added as ready???

**Comment by samhatoum** [comment]
Thanks for pointing it out @maxmckenzie. Must have been error on my part when using waffle.io/xolvio/chimp

**Comment by maxmckenzie** [comment]
i do have a related question... when running mocha without chimp i do not have to choose a browser to run in as its a unit test. Why does it need to use chrome i nthis instance???

**Comment by samhatoum** [comment]
chimp is an acceptance and end-to-end test runner, and it allows you to use mocha/cucumber/jasmine to do write those tests.

question for you, why do you need chimp if you don't need chrome? why not just run `mocha <your tests>`

**Comment by maxmckenzie** [comment]
touché sir... well its because I do intend on adding end to end tests as well. so as a structure i have

```
features/
  unit/
   index.js
  e2e/
   a.feature
   steps/
    global.js
```

**Comment by samhatoum** [comment]
gotcha. I would use mocha standalone to run your unit tests, and then use chimp to run the ones tests that need a browser. See here:

https://github.com/xolvio/qualityfaster/blob/dev/package.json#L15-L18

HTH

**Comment by maxmckenzie** [comment]
here is what i ended up doing for my scripts.

```
"scripts": {
    "start": "node dist/index.js",
    "dev": "nodemon --exec \"concurrently 'babel-node src/index.js' 'npm run test'\"",
    "build": "babel src -d dist",
    "test": "npm run test:unit && npm run test:e2e",
    "test:e2e": "chimp",
    "test:unit": "mocha --compilers js:babel-register"
  },
```

`npm run dev` creates a dev server and runs the test. using nodemon on each change it reboots the server and runs the tests again.

I thought that was pretty swanky and a lot easier than the app.listen() or server.close methods i've seen to avoid EDDRINUSE error when passing --watch into mocha or chimp.  mentioned in this blog post http://www.marcusoft.net/2015/10/eaddrinuse-when-watching-tests-with-mocha-and-supertest.html

**Comment by samhatoum** [comment]
cool. you can also use https://github.com/daaku/nodejs-freeport

Also, if you want to chat, come to the xolv.io/community
