### ISSUE TITLE
Test hangs if some actions with non-existent element performed

### ISSUE THREAD

**Issue by faizrr** [xolvio/chimp#564]
When I use chromedriver and perform `browser.element()` for non-existent element selector, test hangs on the step where it was mentioned and other steps don't perform.

Also, this problem doesn't occur on phantomjs.

Here's the test:
```javascript
describe('Test', () => {
  before(() => {
    browser.url('http://google.com')
  })

  it('test one', () => {
    const element = browser.element('foo')
    expect(element.isExisting()).to.be.false
  })

  it('test two', () => {
    const element = browser.element('body')
    expect(element.isExisting()).to.be.true
  })
})
```

#####  Expected behaviour

```
Test
    ✓ test one
    ✓ test two


  2 passing (2s)
```

#####  Actual behaviour
```
  Test
    1) test one
    2) test two


  0 passing (11s)
  2 failing

  1) Test test one:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
  

  2) Test test two:
     TypeError: element.isExisting is not a function
      at Context.<anonymous> (tests/feature/desktop/simple.js:13:20)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
```

##### Exact steps to reproduce / repository that demonstrates the problem
Here's the config for chimp:
```javascript
{
  browser: 'chrome',
  mocha: true,
  mochaConfig: {
    timeout: 10000
  },
  watch: true
}
```

Log if chrome is used: https://gist.github.com/faizrr/e8123c67d1e0033eba15e62cbb46ea9b
Log if phantomjs is used: https://gist.github.com/faizrr/c8470f5227a2c36fb3289348fbb268c6

#####  Version & tools:

* Chimp: 0.45.1
* Node.js: 6.7.0
* Java: 1.8.0_101
* Operation system: macOS 10.12.2

Also, I tried to run plain webdriver.io locally and I couldn't experience such error.

**Comment by faizrr** [comment]
Found similar issue. But it was fixed. https://github.com/webdriverio/webdriverio/issues/1466

**Comment by lucetius** [comment]
We can't reproduce the issue. Try to run newest Chimp version. You can also try to remove `browser` from your config file. This way you will be using Chromedriver directly without Java.
Also when you use watch mode in Chimp don't forget to add `@watch` or `@focus` in your tests.
