### ISSUE TITLE
Port error when using gulp-chimp wrapper

### ISSUE THREAD

**Issue by MacDennis76** [xolvio/chimp#566]
Hello,

I would like to use gulp to automate various testing tasks. I am currently trying to get the gulp-chimp wrapper to work but I haven't been successful yet.

#####  Expected behaviour
gulp-chimp wrapper working without errors when using external config file
Config file: https://github.com/eduardogch/gulp-chimp/blob/master/chimp.conf.js

#####  Actual behaviour
Error:

[chimp] Running...
[15:52:08] 'chimp' errored after 56 ms
[15:52:08] Error: options.port is required

##### Exact steps to reproduce / repository that demonstrates the problem
Run gulp-chimp example as stated in the Chimp installation instructions.

#####  Version & tools:
Chimp: 0.47.1
Node.js: 6.9.4
Java: 1.8.0_91 9 (64 bit)
Operation system: Windows10 64bit

#####  Console / Log Output
[chimp] Running...
[15:52:08] 'chimp' errored after 56 ms
[15:52:08] Error: options.port is required
    at new Selenium (D:\temp\chimp2\node_modules\gulp-chimp\node_modules\chimp\dist\lib\selenium.js:29:11)
    at Chimp._createProcesses (D:\temp\chimp2\node_modules\gulp-chimp\node_modules\chimp\dist\lib\chimp.js:532:22)
    at Chimp._startProcesses (D:\temp\chimp2\node_modules\gulp-chimp\node_modules\chimp\dist\lib\chimp.js:490:25)
    at D:\temp\chimp2\node_modules\gulp-chimp\node_modules\chimp\node_modules\async\lib\async.js:607:21
    at D:\temp\chimp2\node_modules\gulp-chimp\node_modules\chimp\node_modules\async\lib\async.js:246:17
    at iterate (D:\temp\chimp2\node_modules\gulp-chimp\node_modules\chimp\node_modules\async\lib\async.js:146:13)
    at D:\temp\chimp2\node_modules\gulp-chimp\node_modules\chimp\node_modules\async\lib\async.js:157:25
    at D:\temp\chimp2\node_modules\gulp-chimp\node_modules\chimp\node_modules\async\lib\async.js:248:21
    at D:\temp\chimp2\node_modules\gulp-chimp\node_modules\chimp\node_modules\async\lib\async.js:612:34
    at Chimp.interrupt (D:\temp\chimp2\node_modules\gulp-chimp\node_modules\chimp\dist\lib\chimp.js:432:5)
    at D:\temp\chimp2\node_modules\gulp-chimp\node_modules\chimp\node_modules\async\lib\async.js:607:21
    at D:\temp\chimp2\node_modules\gulp-chimp\node_modules\chimp\node_modules\async\lib\async.js:246:17
    at iterate (D:\temp\chimp2\node_modules\gulp-chimp\node_modules\chimp\node_modules\async\lib\async.js:146:13)
    at async.eachSeries (D:\temp\chimp2\node_modules\gulp-chimp\node_modules\chimp\node_modules\async\lib\async.js:162:9)
    at _asyncMap (D:\temp\chimp2\node_modules\gulp-chimp\node_modules\chimp\node_modules\async\lib\async.js:245:13)
    at Object.mapSeries (D:\temp\chimp2\node_modules\gulp-chimp\node_modules\chimp\node_modules\async\lib\async.js:228:23)

Thanks!

**Comment by MacDennis76** [comment]
This is not a Chimp issue. Issue was solved with the help of the gulp-chimp author: https://github.com/eduardogch/gulp-chimp/issues/6
