### ISSUE TITLE
Chimp tests failing as chimp is not registering Meteor / Blaze {{#if currentUser }}, despite automated browser behaving correctly

### ISSUE THREAD

**Issue by B-raw** [xolvio/chimp#568]
#####  Expected behaviour
Chimp tests user flows which are dependent on user being logged in.

In Meteor, on my app homepage:

```
{{#if currentUser}}
  <a href="/initial-assessment" class="btn btn-info btn-lg btn-display-block-sm" id="new-patient2">New Patient</a>
{{else}}
  <a href="/signup" class="btn btn-info btn-lg btn-display-block-sm" id="new-patient">New Patient</a>
  <a href="/signup" class="information-text block-information" id="signup-required">Sign Up Required</a>
{{/if}}
```

I expect Chimp to be able to find selector `#new-patient2` when logged in and click on it.

#####  Actual behaviour
`Error: An element could not be located on the page using the given search parameters.`

On the automated browser which loads, I can see that the correct element has loaded by inspecting the element - `#new-patient2` is present.

However chimp behaves as though '#new-patient2' is not on the page. It seems to think that there is no `currentUser`.

Is there a bug with chimp and Meteor or Blaze's `currentUser`?

##### Exact steps to reproduce / repository that demonstrates the problem
1. `git clone https://github.com/B-raw/cardiac_algorithm.git`
2. change to branch "navbar" `git checkout navbar`
3. launch app `meteor`
4. run @watch version of chimp (using my package.json script) `npm run test-watch`
5. the above steps should confirm that the chimp does not recognise that it is logged in
6. to confirm that the logic is working properly otherwise:
a) view the chimp browser GUI that pops up and confirm that the test should be passing - inspect element on the button `New Patient` - this has an id `new-patient2`
b) can also use app manually on localhost:3000 to confirm

#####  Version & tools:

* Chimp command line used: `chimp --ddp=http://localhost:3000 --mocha --watch --path=tests || exit 0` run via `npm run test-watch` from my package.json file
* Chimp config file: *Please provide a Gist if you use a config file*
* Chimp: 0.47.1
* Node.js: v6.9.4
* Java: 
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
* Operation system: 
Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64

#####  Console / Log Output

```
    ✓ can register a new user @watch
    when logged in
      1) shows algorithm when click on "New Patient" @watch


  1 passing (5s)
  1 failing

  1) User registration when logged in shows algorithm when click on "New Patient" @watch:
     Error: An element could not be located on the page using the given search parameters.
      at Context.<anonymous> (tests/registrationFeature.js:84:15)
      at /Users/michael/.nvm/versions/node/v6.9.4/lib/node_modules/chimp/dist/lib/utils/fiberize.js:25:14

##### NB I also have intermittently had this problem with the navbar - switching "Log In | Sign Up" to "My Account | Log Out" using the same method of {{ #if currentUser }}. This intermittently works, and then fails for no clear reason.

You can see that logic in this file:
https://github.com/B-raw/cardiac_algorithm/blob/navbar/imports/ui/layouts/navbar.html
```

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by B-raw** [comment]
Spent ages on this problem and seems to have been a problem with me not using a `waitForExist` block - apologies. **Embarrassed!**
