### ISSUE TITLE
Embeding screenshots in JSON output causes Chimp to crash.

### ISSUE THREAD

**Issue by tiagolr** [xolvio/chimp#575]
using the following chimp configs:

```js
screenshotsOnError: true,
saveScreenshotsToReport: true,
jsonOutput: './e2e-results.json',
```

causes following error after the tests finish running:

```
/node_modules/chimp/dist/lib/cucumberjs/cucumber.js:101
          if (_this.options.jsonOutput && JSON.parse(jsonResults).length) {
                                                                 ^

TypeError: Cannot read property 'length' of null
    at ChildProcess.<anonymous> (node_modules/chimp/dist/lib/cucumberjs/cucumber.js:101:66)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

The problem does not happen if the screenshots are saved on disk instead of embed in the json output.

**Comment by lucetius** [comment]
Please provide steps to reproduce problem. You forgot attach necessary information from issue template like version and tools used.

**Comment by tiagolr** [comment]
Ok my bad,

I created a repository for the issue, its very easy to reproduce the problem now:

```
git clone https://github.com/tiagolr/chimp-575.git
cd chimp-575
npm i
npm test
```

Thank you!
