### ISSUE TITLE
chimp tests not running - setupBrowserAndDDP had error

### ISSUE THREAD

**Issue by tomaszzar** [xolvio/chimp#578]
#####  Expected behaviour
Chimp tests run as normal.

#####  Actual behaviour
Chimp tests don't run.

#####  Version & tools:

* Chimp command line used: 
```
chimp .config\chimp.js --ddp=http://localhost:3000
```
* Chimp config file: 
```
module.exports = {  
// - - - - WEBDRIVER-IO  - - - -
  webdriverio: {
    desiredCapabilities: {},
    logLevel: 'silent',
    // logOutput: null,
    host: '127.0.0.1',
    port: 4444,
    path: '/wd/hub',
    baseUrl: null,
    coloredLogs: true,
    screenshotPath: null,
    waitforTimeout: 10000,
    waitforInterval: 250,
  },
}
```
* Chimp: 0.9.4
* Node.js: v5.11.0
* Java:
 java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
* Operation system: Windows_NT 10.0.10586

#####  Console / Log Output

```
[chimp] Running...
[chimp][helper] setupBrowserAndDDP had error
{ [Error: Connection reset]
  message: 'Connection reset',
  type: 'RuntimeError',
  seleniumStack:
   { status: 13,
     type: 'UnknownError',
     message: 'An unknown server-side error occurred while processing the command.',
     orgStatusMessage: 'Connection reset' } }
Error: Connection reset
    at Object.Future.wait (c:\Program Files\node_modules\fibers\future.js:449:15)
    at Object.<anonymous> (c:\Program Files\node_modules\wdio-sync\build\index.js:345:27)
    at initBrowser (c:\Program Files\node_modules\chimp\dist\lib\chimp-helper.js:168:17)
    at Object.setupBrowserAndDDP (c:\Program Files\node_modules\chimp\dist\lib\chimp-helper.js:226:7)
    at c:\Program Files\node_modules\chimp\dist\lib\cucumberjs\hooks.js:21:24
    at c:\Program Files\node_modules\meteor-promise\fiber_pool.js:33:40
    - - - - -
    at new RuntimeError (c:\Program Files\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:115:12)
    at Request._callback (c:\Program Files\node_modules\webdriverio\build\lib\utils\RequestHandler.js:257:39)
    at Request.self.callback (c:\Program Files\node_modules\webdriverio\node_modules\request\request.js:373:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (c:\Program Files\node_modules\webdriverio\node_modules\request\request.js:1318:14)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (c:\Program Files\node_modules\webdriverio\node_modules\request\request.js:1266:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Cucumber steps failed
```

Any help? : )

**Comment by tomaszzar** [comment]
My environment variables were pointing to the wrong directory of node_modules. After fixing that and reinstalling Chimp everything works fine.
