### ISSUE TITLE
Chimp stopped working

### ISSUE THREAD

**Issue by thebarty** [xolvio/chimp#604]
Hi guys,

for some reason Chimp does NOT work anymore on my OSX. After getting the error "unknown error: cannot get automation extension", I did a `npm install -g chimp`.

After the update the most simple command `browser.url()` will NOT load the url. 
Chimp opens up chrome, BUT chrome now give a popup-message "Chrome is remote controlled by testing-software" and does **NOT load the url**, resulting my tests in failing.

Any ideas what to do?

#####  Version & tools
Chimp 0.47.2
Node v4.6.2
Java Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
OSX Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64

**Comment by samhatoum** [comment]
Hey @thebarty 

Is this a completely new project? If not try that first please

**Comment by thebarty** [comment]
@samhatoum : Thanks a lot for the hyperfast response.

It is an existing project.

Good news is that when I create a blank meteor-project it works... 

so what might be the reason for the existing project failing?

**Comment by samhatoum** [comment]
np. try killing your node_modules directories and running install again

**Comment by thebarty** [comment]
Ok, still no luck. This is what I did:

```
# in project root
cd node_modules
rm -r *
cd ..
meteor npm install
npm -g uninstall chimp
npm -g install chimp
```

Still no luck.

Did you mean the global node_modules? Can I simply whipe that away?

**Comment by thebarty** [comment]
@samhatoum : Do you have any other suggestions what to try?

*For future reference it would be nice to have some kind of trouble-guide for resetting chimp in those cases.*

**Comment by danhounshell** [comment]
I ran into the "unknown error: cannot get automation extension" issue this morning after having successfully run tests just as recently as yesterday afternoon. The chromedriver version that chimp is using is 27.2.2 which apparently has an issue with Chrome 57+. Chrome must have updated overnight or this morning to the newest version. Chromedriver 2.28.0 is supposed to correct that issue: https://chromedriver.storage.googleapis.com/2.28/notes.txt

**Comment by thebarty** [comment]
@danhounshell : That sounds really promising. Now I have to find a way to install your fork locally (have never done that before). Do you have  a quick hint?

@samhatoum : Does this one work for you? Do you think you can merge it in?

**Comment by thebarty** [comment]
this sucks so much. My frontend development workflow is broken. 

I already wasted 1 hour trying to locally patch chimp (did not get it to work yet), also downgrading local chrome on osx is not an easy thing to do. You got to load some unsecure binary off an archive website, which I do not want to do.

**Comment by lgandecki** [comment]
@thebarty Try this:

remove chimp from package.json , 
rm -rf node_modules
npm install github:danhounshell/chimp#fix-chromedriver-2-28 --save
npm install

**Comment by thebarty** [comment]
@lgandecki Thanks for your help!

Unfortunatly it did NOT work. I am getting a 
```
Cannot find module '../dist/bin/chimp'
```

Any suggestions?

**Comment by lgandecki** [comment]
@thebarty  I will need more information than that, show me more logs, and also what caused you to get this error? What did you try run?

**Comment by thebarty** [comment]
@lgandecki : ok lets try to reproduce:

starting fresh:

```
cd src;  # source of my project
rm -rf node_modules
npm uninstall -g chimp  # I had it installed globally
# install local fork
npm install github:danhounshell/chimp#fix-chromedriver-2-28 --save-dev
# get path to local npm
npm bin # /Users/thebarty/meteor/projectsrc/node_modules/.bin
# call chimp locally
/Users/thebarty/meteor/projectsrc/node_modules/.bin/chimp
```

results in 

```
module.js:327
    throw err;
    ^

Error: Cannot find module '../dist/bin/chimp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/thebarty/meteor/projectsrc/node_modules/.bin/chimp/bin/chimp.js:4:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
````

Any ideas?

**Comment by lgandecki** [comment]
Yes, we are missing a step here, when you install directly from github the chimp is not "build". 
Give me a couple minutes..

**Comment by lgandecki** [comment]
ok, @thebarty , I'm not sure why yet but when we do npm install from that branch the chimp ends up not having src and scripts folders.
So, what made it start for me was:
cd node_modules
rm -rf chimp
git clone https://github.com/danhounshell/chimp.git -b fix-chromedriver-2-28
cd chimp
npm install
then you should be able to cd ../../ and run chimp with 
/Users/thebarty/meteor/projectsrc/node_modules/.bin/chimp

Let us know if that helps, if it does, we will move forward with applying changes from that branch and publish a new chimp version

Thanks a lot and sorry for the problem!

**Comment by thebarty** [comment]
@lgandecki : ok, I can now run chimp, but I am seeing the same problem. Chrome opens up, but shows me a "chrome is being steered by test-automation-software". And it is NOT able to load the url via `browser.url` Damn! 

Is there a way to check which chromedriver is running?

**Comment by thebarty** [comment]
Hi guys,

my chimp still isn't running.

Does anyone have an idea what else to try?

**Comment by etyp** [comment]
@thebarty any luck since 2 days ago?

**Comment by thebarty** [comment]
@etyp Thanks for asking! 👍 

Unfortunatly NO. I don't really know what else to try... ???

Do you have the same problem, or an idea what else to try?

**Comment by thebarty** [comment]
Hi guys,

still do NOT have it working. I just tried the debug options and got the following report.

It says I have "Browser version:  chrome 57.0.2987.133" and "chromedriverVersion":"2.29.461585".

**Any ideas what else to try?**
```
Browser version:  chrome 57.0.2987.133
[chimp] Watching features with tagged with @watch

[chimp] Running...


[chimp][helper] Using the chai-expect assertion library
[chimp][ddp] creating DDP wrapper
[chimp][ddp] Connecting to DDP server { host: 'localhost',
  port: '3100',
  ssl: false,
  path: undefined,
  autoReconnect: true,
  autoReconnectTimer: 500,
  maintainCollections: true,
  ddpVersion: '1',
  useSockJs: true }
[chimp][ddp] creating DDP wrapper
[chimp][ddp] Connecting to DDP server { host: 'localhost',
  port: '3100',
  ssl: false,
  path: undefined,
  autoReconnect: true,
  autoReconnectTimer: 500,
  maintainCollections: true,
  ddpVersion: '1',
  useSockJs: true }
[chimp][helper] getting browser
[chimp][session-manager-factory] options are { host: 'localhost',
  port: 52127,
  user: undefined,
  key: undefined,
  browser: 'chrome',
  deviceName: undefined }
[chimp][session-manager] created a new SessionManager
[chimp][helper] webdriverioOptions are  {"desiredCapabilities":{"browserName":"chrome","platform":"ANY","name":"","applicationCacheEnabled":false},"logLevel":"verbose","host":"localhost","port":52127,"path":"/wd/hub","baseUrl":null,"coloredLogs":true,"screenshotPath":null,"waitforTimeout":10000,"waitforInterval":250,"sync":true}
[chimp][session-manager] creating webdriver remote 

=======================================================================================
Selenium 2.0 / webdriver protocol bindings implementation with helper commands in nodejs.
For a complete list of commands, visit http://webdriver.io/api.html.
=======================================================================================

[chimp][session-manager] checking connection to selenium server
[14:08:16]  COMMAND	GET 	 "/wd/hub/status"
[14:08:16]  DATA		{}
[14:08:16]  RESULT		{"build":{"version":"alpha"},"os":{"arch":"x86_64","name":"Mac OS X","version":"10.11.6"}}
[chimp][session-manager] Connection to the to selenium server verified
[chimp][session-manager] requesting sessions from http://localhost:52127/wd/hub/sessions
[chimp][session-manager] received data {"sessionId":"","status":0,"value":[]}
[chimp][session-manager] Did not find any open selenium sessions, not reusing a session
[chimp][session-manager] monkey patching the browser object
[chimp][hooks] init browser
[chimp][hooks] init browser callback
[chimp][session-manager] initializing browser
[14:08:16]  COMMAND	POST 	 "/wd/hub/session"
[14:08:16]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","platform":"ANY","name":"","applicationCacheEnabled":false,"loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.6.2","name":"webdriverio"}}}
[14:08:17]  INFO	SET SESSION ID 0b6641a3fa77f03b7835d2342b907fb3
[14:08:17]  RESULT		{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"chromedriverVersion":"2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b)","userDataDir":"/var/folders/j3/hmkt_82519vbmq40ccj1c97c0000gn/T/.org.chromium.Chromium.i9uHwp"},"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":false,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platform":"Mac OS X","rotatable":false,"takesHeapSnapshot":true,"takesScreenshot":true,"unexpectedAlertBehaviour":"","version":"57.0.2987.133","webStorageEnabled":true}
[chimp][helper] init browser
[chimp][helper] init browser callback
[chimp][helper] setup DDP
[chimp][helper] connecting via DDP to http://localhost:3100
[chimp][helper] connecting via DDP to localhost:3100
[chimp][helper] connecting via DDP had no error
  SetupWizard
[14:08:17]  COMMAND	DELETE 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/cookie"
[14:08:17]  DATA		{}
[14:08:17]  RESULT		null
[14:08:17]  COMMAND	GET 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/url"
[14:08:17]  DATA		{}
[14:08:17]  RESULT		"data:,"
                 *   waiting for element to exist "div#__blaze-root"
[14:08:17]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:17]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:17]  RESULT		[]
[14:08:17]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:17]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:17]  RESULT		[]
[14:08:17]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:17]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:17]  RESULT		[]
[14:08:18]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:18]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:18]  RESULT		[]
[14:08:18]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:18]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:18]  RESULT		[]
[14:08:18]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:18]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:18]  RESULT		[]
[14:08:18]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:18]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:18]  RESULT		[]
[14:08:19]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:19]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:19]  RESULT		[]
[14:08:19]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:19]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:19]  RESULT		[]
[14:08:19]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:19]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:19]  RESULT		[]
[14:08:19]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:19]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:19]  RESULT		[]
[14:08:20]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:20]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:20]  RESULT		[]
[14:08:20]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:20]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:20]  RESULT		[]
[14:08:20]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:20]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:20]  RESULT		[]
[14:08:20]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:20]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:20]  RESULT		[]
[14:08:21]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:21]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:21]  RESULT		[]
[14:08:21]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:21]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:21]  RESULT		[]
[14:08:21]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:21]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:21]  RESULT		[]
[14:08:21]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:21]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:21]  RESULT		[]
[14:08:22]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:22]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:22]  RESULT		[]
[14:08:22]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:22]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:22]  RESULT		[]
[14:08:22]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:22]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:22]  RESULT		[]
[14:08:22]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:22]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:22]  RESULT		[]
[14:08:23]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:23]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:23]  RESULT		[]
[14:08:23]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:23]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:23]  RESULT		[]
[14:08:23]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:23]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:23]  RESULT		[]
w[14:08:23]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:23]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:23]  RESULT		[]
[14:08:24]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:24]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:24]  RESULT		[]
[14:08:24]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:24]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:24]  RESULT		[]
[14:08:24]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:24]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:24]  RESULT		[]
[14:08:24]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:24]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:24]  RESULT		[]
[14:08:25]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:25]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:25]  RESULT		[]
[14:08:25]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:25]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:25]  RESULT		[]
[14:08:25]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:25]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:25]  RESULT		[]
[14:08:25]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:25]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:25]  RESULT		[]
[14:08:26]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:26]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:26]  RESULT		[]
[14:08:26]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:26]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:26]  RESULT		[]
[14:08:26]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:26]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:26]  RESULT		[]
[14:08:26]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:26]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:26]  RESULT		[]
[14:08:27]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:27]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:27]  RESULT		[]
[14:08:27]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:27]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:27]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:27]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:27]  RESULT		[]
[14:08:27]  RESULT		[]
                   *   element div#__blaze-root does NOT exist after timeout! This is some data for debug
[14:08:27]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:27]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:27]  RESULT		[]
browser.isExisting(div#__blaze-root) false
[14:08:27]  COMMAND	POST 	 "/wd/hub/session/0b6641a3fa77f03b7835d2342b907fb3/elements"
[14:08:27]  DATA		{"using":"css selector","value":"div#__blaze-root"}
[14:08:27]  RESULT		[]
browser.isVisible(div#__blaze-root) false
    1) "before each" hook

[chimp][mocha-helper] Ending browser session
[chimp][session-manager] watch / server mode are true, not killing session
[chimp][mocha-helper] Ended browser sessions

  0 passing (11s)
  1 failing

  1) SetupWizard "before each" hook:
     Uncaught Error: element (div#__blaze-root) still not existing after 10000ms
      at Function.waitForExist (tests/_stabelize.js:161:15)
      at Function.initBrowserDatabaseAndUser (tests/_chimp_helper.js:36:15)
      at Context.<anonymous> (tests/setup_wizard.acceptance.test.js:18:17)
      at node_modules/chimp/dist/lib/utils/fiberize.js:29:22
```

**Comment by thebarty** [comment]
OK guys,

thanks a lot to all of you helping out!!!

I found the solution. It was freakin easy and took me way too long to find.

For some reason `process.env['chimp.ddp']` was NOT `undefined` and is now available at `process.env['chimp.ddp0']`. I am setting the url dynamically using this, as I am running it on CI.

So this was NOT chimps fault, as I was simply calling `browser.url(undefined)`, which OF COURSE will NOT work.

OK, so this is the code that now works for me. I have added a guard to product this from coming up again.

```
// read url from node bash,  p.e. when calling chimp like `chimp --ddp=http://localhost:3200`
const url = process.env['chimp.ddp'] || process.env['chimp.ddp0']
if (!url) {
  throw new Error('CHIMP URL not available via process.env. Whats wrong here? See 00_test_settings.js')
}
console.log('PROCESSING CHIMP AT URL', url)  // eslint-disable-line

export const TestSettings = {
  url,
  // ...
}
```

**Comment by dkoo761** [comment]
If anyone's having issues running Chimp after upgrading to the latest Chrome 63 (specifically an error that looks like this:

```
[chimp] Detected an unhandledRejection:
[chimp][hooks] Error: connect ECONNREFUSED 127.0.0.1:55828
    at Object.saveScreenshotsToDisk (.scripts/node_modules/chimp/dist/lib/screenshot-helper.js:16:28)
    at .scripts/node_modules/chimp/dist/lib/cucumberjs/hooks.js:60:26
    at .scripts/node_modules/meteor-promise/fiber_pool.js:32:39
```

I was able to get it working by uninstalling Chimp and then reinstalling it. My package.json had a Chimp devDepencency of `"chimp": "^0.49"` so the Chimp reinstall upgraded it from 0.49.0 to 0.49.1 and (among other dependencies) also upgraded it's chromedriver dependency from 2.29.0 to 2.34.1. chromedriver appears to be pegged to ^2.27.2 in Chimp's package.json so not sure why Chimp seems to be pulling in a newer version, but hey, it works :)
```
