### ISSUE TITLE
Incorrect ERROR when an element is not found with webdriverio using cucumber

### ISSUE THREAD

**Issue by asanchezgiraldo** [xolvio/chimp#609]
Expected behaviour

When steps fail due to element not being found, a simple Element not found ERROR and class name should be displayed

Actual behaviour

The below error is displayed when and ELEMENT is not found.

```
[12:02:54][Step 4/4]  [31m[chimp] Detected an unhandledRejection: [39m
[12:02:54][Step 4/4]  [31m[chimp][hooks] [39m TypeError: Cannot read property 'ELEMENT' of null
[12:02:54][Step 4/4]     at is$$Result (/home/ubuntu/buildAgent/work/b9511fa8232fb94c/automation/node_modules/wdio-sync/build/index.js:348:63)
[12:02:54][Step 4/4]     at Object.applyPrototype (/home/ubuntu/buildAgent/work/b9511fa8232fb94c/automation/node_modules/wdio-sync/build/index.js:363:199)
[12:02:54][Step 4/4]     at Object.<anonymous> (/home/ubuntu/buildAgent/work/b9511fa8232fb94c/automation/node_modules/wdio-sync/build/index.js:322:63)
[12:02:54][Step 4/4]     at Object.exec (/home/ubuntu/buildAgent/work/b9511fa8232fb94c/automation/node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
[12:02:54][Step 4/4]     at Object.resolve (/home/ubuntu/buildAgent/work/b9511fa8232fb94c/automation/node_modules/webdriverio/build/lib/webdriverio.js:189:29)
[12:02:54][Step 4/4]     at /home/ubuntu/buildAgent/work/b9511fa8232fb94c/automation/node_modules/webdriverio/build/lib/webdriverio.js:538:32
[12:02:54][Step 4/4]     at _fulfilled (/home/ubuntu/buildAgent/work/b9511fa8232fb94c/automation/node_modules/q/q.js:854:54)
[12:02:54][Step 4/4]     at self.promiseDispatch.done (/home/ubuntu/buildAgent/work/b9511fa8232fb94c/automation/node_modules/q/q.js:883:30)
[12:02:54][Step 4/4]     at Promise.promise.promiseDispatch (/home/ubuntu/buildAgent/work/b9511fa8232fb94c/automation/node_modules/q/q.js:816:13)
[12:02:54][Step 4/4]     at /home/ubuntu/buildAgent/work/b9511fa8232fb94c/automation/node_modules/q/q.js:624:44
[12:02:54][Step 4/4]     at runSingle (/home/ubuntu/buildAgent/work/b9511fa8232fb94c/automation/node_modules/q/q.js:137:13)
[12:02:54][Step 4/4]     at flush (/home/ubuntu/buildAgent/work/b9511fa8232fb94c/automation/node_modules/q/q.js:125:13)
[12:02:54][Step 4/4]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[12:02:54][Step 4/4]     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```
Exact steps to reproduce / repository that demonstrates the problem

Run any tests that try to find an element that does not exist

Version & tools:

Chimp: 0.8
Node.js: 6.1.0
Java: 1.8.0_91
Operation system: Ubuntu 12
Console / Log Output

Join our Slack xolv.io/community #chimp channel, where you can find help and help others.

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
