### ISSUE TITLE
Fails to resize chrome. Updating chromedriver helps.

### ISSUE THREAD

**Issue by SimonSimCity** [xolvio/chimp#665]
#####  Expected behaviour

Resize the browser

#####  Actual behaviour

Fails with an exception

##### Exact steps to reproduce / repository that demonstrates the problem

Call `browser.setViewportSize({ width: 400, height: 250 });` within a test

#####  Version & tools:

* Chimp command line used: `chimp --browser=chrome`
* Chimp config file: default
* Chimp: 0.50.2
* Node.js: 4.8.4
* Java: 1.8.0_66
* Operation system: Mac OS X 10.11.6

#####  Console / Log Output

     Error: unknown error: cannot get automation extension
         at World.<anonymous> (features/browser.js:9:13)
         from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
         at emitTwo (events.js:87:13)
         at Request.emit (events.js:172:7)
         at emitOne (events.js:77:13)
         at Request.emit (events.js:169:7)
         at IncomingMessage.g (events.js:260:16)
         at emitNone (events.js:72:20)
         at IncomingMessage.emit (events.js:166:7)
         at endReadableNT (_stream_readable.js:923:12)
         at nextTickCallbackWith2Args (node.js:511:9)
         at process._tickDomainCallback (node.js:466:17)

##### Additional information

Works by updating the chromedriver.

**Comment by samhatoum** [comment]
this should now be fixed in 0.51 as chromedriver is updates
