### ISSUE TITLE
Cannot run chimp with --browser="MicrosoftEdge" windows 10 latest version

### ISSUE THREAD

**Issue by miendt** [xolvio/chimp#688]
#####  Expected behaviour
- Run web application on Microsoft Edge.
- I want to run chimp with Microsoft Edge. However, when i run command as `chimp .\features\login.feature --browser="MicrosoftEdge"` after installing selenium-standalone about (93%) they have an error.

#####  Actual behaviour
- Cannot launch Microsoft Edge when run chimp

##### Exact steps to reproduce / repository that demonstrates the problem
- install [nodejs](https://nodejs.org/en/)
- install [Oracle JDK v1.8+](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
- npm install -g chimp
- Run test in my project as: `chimp .\features\login.feature --browser="MicrosoftEdge"`

#####  Version & tools:
Chimp version:  0.51.1
ChromeDriver version:  Unknown. Chromedriver not used directly.
Java version:  java version "1.8.0_171", Java(TM) SE Runtime Environment (build 1.8.0_171-b11), Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
Selenium version:  3.8.1
Selenium drivers version:  chrome: 2.35, ie: 3.0.0, firefox: 0.19.1
OS version:  Windows_NT 10.0.16299
Node version:  v8.11.1

* Chimp command line used: *The exact command you used*
==> `chimp .\features\login.feature --browser="MicrosoftEdge"`
* Chimp config file: *Please provide a Gist if you use a config file*
=> npm install -g chimp
* Chimp: *type `chimp -v`*
=> v0.51.1
* Node.js: *type `node -v`*
=> v8.11.1
* Java: *type `java -version`*
=> 1.8.0_171
* Operation system: *type `uname -v`*
=> Windows_NT 10.0.16299
*Microsoft Edge:*
=> Microsoft Edge 41.16299.248.0
=> Microsoft EdgeHTML 16.16299

#####  Console / Log Output
- When i use `--debug` log output as:
```
Chimp version:  0.51.1
ChromeDriver version:  Unknown. Chromedriver not used directly.
Java version:  java version "1.8.0_171", Java(TM) SE Runtime Environment (build 1.8.0_171-b11), Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
Selenium version:  3.8.1
Selenium drivers version:  chrome: 2.35, ie: 3.0.0, firefox: 0.19.1
OS version:  Windows_NT 10.0.16299
Node version:  v8.11.1
Browser version:  MicrosoftEdge Driver for selected browser(MicrosoftEdge) not found.
```
Seems they not found **driver.version: unknown** of EdgeDriver
```
(node:4668) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client
[chimp][helper] setupBrowserAndDDP had error
{ Error: Unable to create new service: EdgeDriverService
    Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
    System info: host: 'CPP00007556C', ip: '192.168.86.150', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
    Driver info: driver.version: unknown
    at new RuntimeError (C:\Users\huonglt1\AppData\Roaming\npm\node_modules\chimp\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at Request._callback (C:\Users\huonglt1\AppData\Roaming\npm\node_modules\chimp\node_modules\webdriverio\build\lib\utils\RequestHandler.js:316:39)
    at Request.self.callback (C:\Users\huonglt1\AppData\Roaming\npm\node_modules\chimp\node_modules\webdriverio\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\huonglt1\AppData\Roaming\npm\node_modules\chimp\node_modules\webdriverio\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\huonglt1\AppData\Roaming\npm\node_modules\chimp\node_modules\webdriverio\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  details: undefined,
  message: 'Unable to create new service: EdgeDriverService\nBuild info: version: \'3.8.1\', revision: \'6e95a6684b\', time: \'2017-12-01T19:05:32.194Z\'\nSystem info: host: \'CPP00007556C\', ip: \'192.168.86.150\', os.name: \'Windows 10\', os.arch: \'amd64\', os.version: \'10.0\', java.version: \'1.8.0_171\'\nDriver info: driver.version: unknown',
  type: 'RuntimeError',
  seleniumStack:
   { type: 'SessionNotCreatedException',
     message: 'A new session could not be created.',
     orgStatusMessage: 'Unable to create new service: EdgeDriverService\nBuild info: version: \'3.8.1\', revision: \'6e95a6684b\', time: \'2017-12-01T19:05:32.194Z\'\nSystem info: host: \'CPP00007556C\', ip: \'192.168.86.150\', os.name: \'Windows 10\', os.arch: \'amd64\', os.version: \'10.0\', java.version: \'1.8.0_171\'\nDriver info: driver.version: unknown' } }
Error: Unable to create new service: EdgeDriverService
    Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
    System info: host: 'CPP00007556C', ip: '192.168.86.150', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
    Driver info: driver.version: unknown
    at new RuntimeError (C:\Users\huonglt1\AppData\Roaming\npm\node_modules\chimp\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at Request._callback (C:\Users\huonglt1\AppData\Roaming\npm\node_modules\chimp\node_modules\webdriverio\build\lib\utils\RequestHandler.js:316:39)
    at Request.self.callback (C:\Users\huonglt1\AppData\Roaming\npm\node_modules\chimp\node_modules\webdriverio\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\huonglt1\AppData\Roaming\npm\node_modules\chimp\node_modules\webdriverio\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\huonglt1\AppData\Roaming\npm\node_modules\chimp\node_modules\webdriverio\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
Cucumber steps failed
```

Please help me!

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
