### ISSUE TITLE
Couldn't connect Chimp to TestObject cloud service

### ISSUE THREAD

**Issue by miendt** [xolvio/chimp#689]
#####  Expected behaviour
- I want to run automation testing on [TestObject](https://testobject.com/)
- I am using chimp, webdriverio, cucumberjs
- And connect Chimp to [TestObject](https://testobject.com/)

#####  Actual behaviour
- I couldn't connect chimp to [TestObject](https://testobject.com/)

##### Exact steps to reproduce / repository that demonstrates the problem
- This is `chimp-config.js` file:
```
module.exports = {
  deviceName: 'LG_Nexus_5X_free',
  webdriverio: {
    protocol: 'https',
    host: 'us1.appium.testobject.com',
    port: "443",
    path: '/wd/hub',
    desiredCapabilities: {
      testobject_api_key: "{my_key}",
      platformName: "Android",
      testobject_session_creation_timeout: 3600000,
      testobject_session_creation_retry: 120000
    }
  }
}

```

#####  Version & tools:

* Chimp command line used: *The exact command you used*:  `chimp chimp-config.js features/signin.feature`
* Chimp config file: *Please provide a Gist if you use a config file*: As `chimp-config.js` file  above
* Chimp: *type `chimp -v`*: 5.1.0
* Node.js: *type `node -v`*: 8.10.0
* Java: *type `java -version`*: java version "1.8.0_152"
* Operation system: *type `uname -v`*: Mac OS - 10.13.4

#####  Console / Log Output
```
[chimp][helper] setupBrowserAndDDP had error
{ Error: socket hang up
    at new RuntimeError (/Users/miendt/.nvm/versions/node/v8.10.0/lib/node_modules/chimp/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (/Users/miendt/.nvm/versions/node/v8.10.0/lib/node_modules/chimp/node_modules/webdriverio/build/lib/utils/RequestHandler.js:330:43)
    at self.callback (/Users/miendt/.nvm/versions/node/v8.10.0/lib/node_modules/chimp/node_modules/webdriverio/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/Users/miendt/.nvm/versions/node/v8.10.0/lib/node_modules/chimp/node_modules/webdriverio/node_modules/request/request.js:878:8)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  details: undefined,
  message: 'socket hang up',
  type: 'RuntimeError',
  seleniumStack:
   { status: -1,
     type: 'ECONNRESET',
     orgStatusMessage: 'socket hang up',
     message: 'Couldn\'t connect to selenium server' } }
Error: socket hang up
    at new RuntimeError (/Users/miendt/.nvm/versions/node/v8.10.0/lib/node_modules/chimp/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (/Users/miendt/.nvm/versions/node/v8.10.0/lib/node_modules/chimp/node_modules/webdriverio/build/lib/utils/RequestHandler.js:330:43)
    at self.callback (/Users/miendt/.nvm/versions/node/v8.10.0/lib/node_modules/chimp/node_modules/webdriverio/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/Users/miendt/.nvm/versions/node/v8.10.0/lib/node_modules/chimp/node_modules/webdriverio/node_modules/request/request.js:878:8)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[chimp][cucumber] Closed with code 2
[chimp][cucumber] Cucumber not in a stopping state
[chimp] Finished running async processes with errors
[chimp] run complete with errors Cucumber steps failed
[chimp] interrupting
[chimp] 2 processes to interrupt
[chimp][cucumber] interrupting cucumber
[chimp][cucumber] kill called on cucumber process with pid 76019
[chimp][cucumber] checking if process exists
[chimp][cucumber] cucumber process does not exists, ignoring
[chimp][chromedriver] interrupt called
[chimp][chromedriver] stopping process
[chimp][chromedriver] kill called on chromedriver process with pid 76018
[chimp][chromedriver] checking if process exists
[chimp][chromedriver] chromedriver process exists, killing it with SIGTERM
Cucumber steps failed
Error in chimp init Cucumber steps failed
```

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

Do you know this, please help me :(
Thanks a lot!

**Comment by eliezercazares** [comment]
Same issue here... TestObject has slight differences with SauceLabs so I think Chimp might need a new implementation to support TestObject.

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
