### ISSUE TITLE
Terminating chimp with Ctrl + C gives error

### ISSUE THREAD

**Issue by Sanjo** [xolvio/chimp#73]
```
TypeError: invalid pid
    at process.kill (node.js:746:15)
    at process.<anonymous> (/home/jonas/projects/chimp/lib/chimp.js:60:13)
    at emitNone (events.js:67:13)
    at process.emit (events.js:166:7)
    at Signal.wrap.onsignal (node.js:790:46)
```

It's this line https://github.com/xolvio/chimp/blob/master/lib/chimp.js#L60 where the pid argument is missing. Has this line any purpose at all? Should it be process.exit()?

**Comment by samhatoum** [comment]
Turns out this is needed for meteor-cucumber to work. It doesn't work on node 4.1.0 but it's needed to close open browsers on 0.10.x
