### ISSUE TITLE
"undefined is not a function" error whenever try to use any WebDriverIO .then() function, specifically with client.execute(...).then()

### ISSUE THREAD

**Issue by ejlofgren** [xolvio/chimp#75]
First, apologies if this turns out to be a n00b error, but I've been unable to solve this ever since I started using Chimp, which is a really great tool!

I'm using Windows 10 and installed the latest version of chimp today (Sep 24, 2015) for this test case (npm install chimp) and when running I get this error:
```
> .\node_modules\.bin\chimp
[chimp] Running...

Feature: Test case for trying to use .then results in error.

  As a human
  I want to be able to use .then()


  Scenario:                                                       # features\why_is_client_execute_then_not_working_test_case.feature:6
    Given I have visited https://github.com/xolvio/chimp          # features\why_is_client_execute_then_not_working_test_case.feature:7
    When I try to use .then() I get an error in the chimp console # features\why_is_client_execute_then_not_working_test_case.feature:8
      TypeError: undefined is not a function
        at World.<anonymous> (features\support\step_defs.js:12:24)




(::) failed steps (::)

TypeError: undefined is not a function
  at World.<anonymous> (features\support\step_defs.js:12:24)


Failing scenarios:
features\why_is_client_execute_then_not_working_test_case.feature:6 # Scenario:

1 scenario (1 failed)
2 steps (1 failed, 1 passed)

[chimp] Finished running async processes with errors
[chimp] run complete with errors Cucumber steps failed
Error in chimp init Cucumber steps failed
```

The error above occurs with this code, line 12 is the line that has .then():

File: step_defs.js
```
module.exports = function() {
    this.Given(/^I have visited https:\/\/github\.com\/xolvio\/chimp$/, function () {
        client.url("https://github.com/xolvio/chimp");

    });

    this.When(/^I try to use \.then\(\) I get an error in the chimp console$/, function () {
        // Example code from http://webdriver.io/api/protocol/execute.html
        client.execute(function(a, b, c, d) {
            // browser context - you may not access neither client nor console
            return a + b + c + d;
        }, 1, 2, 3, 4).then(function(ret) {
            // node.js context - client and console are available
            console.log(ret.value); // outputs: 10
        });
    });

};
```

File: why_is_client_execute_then_not_working_test_case.feature
```
Feature: Test case for trying to use .then results in error.

  As a human
  I want to be able to use .then()
  
    Scenario:
    Given I have visited https://github.com/xolvio/chimp
    When I try to use .then() I get an error in the chimp console    
```

Let me know if there's any more information you need. I would really like to figure out why I'm unable to use .then() at all.

In case it helps, here's the output from "npm install chimp" and then  in case it provides any helpful info:
```
> npm install chimp
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN deprecated URIjs@1.15.0: package renamed to "urijs" (lower-case), please update accordingly
-
> fibers@1.0.7 install C:\Users\elofgren\Desktop\temp\chimp_install_test\node_modules\chimp\node_modules\fibers
> node build.js || nodejs build.js

`win32-x64-v8-3.28` exists; testing
Binary is fine; exiting
chimp@0.15.4 node_modules\chimp
├── freeport@1.0.5
├── progress@1.1.8
├── chai-as-promised@5.1.0
├── chimp-widgets@0.2.0
├── child-process-debug@0.0.7
├── saucelabs@0.1.1
├── colors@1.1.2
├── minimist@1.2.0
├── async@0.9.2
├── underscore@1.8.3
├── exit@0.1.2
├── loglevel@1.4.0
├── xolvio-jasmine-expect@1.0.0 (jasmine-core@2.3.4)
├── bluebird@2.10.1
├── chai@3.0.0 (assertion-error@1.0.1, type-detect@1.0.0, deep-eql@0.1.3)
├── chokidar@1.0.6 (arrify@1.0.0, path-is-absolute@1.0.0, is-glob@1.1.3, async-each@0.1.6, glob-parent@1.3.0, is-binary-path@1.0.1, readdirp@1.4.0, anymatch@1.3.0)
├── fs-extra@0.24.0 (path-is-absolute@1.0.0, jsonfile@2.2.2, graceful-fs@4.1.2, rimraf@2.4.3)
├── request@2.62.0 (aws-sign2@0.5.0, forever-agent@0.6.1, stringstream@0.0.4, caseless@0.11.0, oauth-sign@0.8.0, tunnel-agent@0.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.3, combined-stream@1.0.5, qs@5.1.0, form-data@1.0.0-rc3, mime-types@2.1.7, http-signature@0.11.0, bl@1.0.0, har-validator@1.8.0, tough-cookie@2.0.0, hawk@3.1.0)
├── ddp@0.11.1 (ddp-ejson@0.8.1-3, ddp-underscore-patched@0.8.1-2, faye-websocket@0.9.4, request@2.53.0)
├── fibers@1.0.7
├── selenium-standalone@4.6.1 (commander@2.6.0, minimist@1.1.0, which@1.1.1, mkdirp@0.5.0, URIjs@1.15.0, async@1.2.1, request@2.51.0, unzip@0.1.11, lodash@3.9.3)
├── hapi@8.8.0 (cryptiles@2.0.4, peekaboo@1.0.0, ammo@1.0.0, accept@1.0.0, items@1.1.0, topo@1.0.2, kilt@1.1.1, catbox-memory@1.1.1, statehood@2.1.1, boom@2.7.2, shot@1.5.3, call@2.0.1, qs@4.0.0, iron@2.1.2, wreck@6.0.0, hoek@2.14.0, catbox@4.3.0, mimos@2.0.2, h2o2@4.0.1, vision@2.0.1, inert@2.1.5, subtext@1.1.1, joi@6.4.1, heavy@3.0.0)
├── xolvio-sync-webdriverio@4.0.5 (xolvio-fiber-utils@2.0.3, meteor-promise@0.4.8, webdriverio@3.2.4)
├── cucumber@0.5.3 (stack-chain@1.3.3, walkdir@0.0.10, nopt@3.0.4, coffee-script@1.10.0, underscore.string@3.2.2, cucumber-html@0.2.3, pogo@0.10.0, browserify@5.11.1, gherkin@2.12.2)
└── phantomjs-bin@1.0.1
```

Any help or pointers are appreciated, thanks!

**Comment by samhatoum** [comment]
Hi

Please see this:

https://chimp.readme.io/docs/v0140-breaking-changes

I'm about to make an announcement :)

**Comment by samhatoum** [comment]
Chimp is now synchronous by default. This will make your life much easier in the long run

**Comment by ejlofgren** [comment]
Thank you very much! 

For anyone else who sees this issue: The key point from https://chimp.readme.io/docs/v0140-breaking-changes is "All the WebdriverIO commands, request and the DDP server connection are already made synchronous for you by default." 

And here's an example of how the syntax needs to be changed from what is listed on http://webdriver.io/api/protocol/execute.html

Instead of:

```
client.execute(function(a, b, c, d) {
    // browser context - you may not access neither client nor console
    return a + b + c + d;
}, 1, 2, 3, 4).then(function(ret) {
    // node.js context - client and console are available
    console.log(ret.value); // outputs: 10
});
```

Use:
```
var ret = client.execute(function(a, b, c, d) {
            // browser context - you may not access neither client nor console
            return a + b + c + d;
        }, 1, 2, 3, 4);
        // node.js context - client and console are available
        console.log(ret.value); // outputs: 10
```

**Comment by samhatoum** [comment]
Thank you for posting back your experience
